"""
Static snapshots of NSE index constituents, for the Batch Analysis ticker
picker's built-in presets.

IMPORTANT: NSE rebalances Nifty 50 / Nifty Next 50 semi-annually (cutoff
dates Jan 31 and Jul 31), so these lists WILL drift out of date. Each list
below is dated. For anything where precision matters, verify against
https://www.niftyindices.com or use the "Custom list" / "Upload CSV"
options in the Batch Analysis tab instead of these presets - that's the
reliable long-term path, not re-editing this file every rebalance.

Symbols are plain NSE symbols (no .NS suffix) - get_ticker_list() below
appends .NS to match this app's ticker convention.
"""

NIFTY_50_AS_OF = "2025-12-08"
# NOTE: TMPV (Tata Motors Passenger Vehicles) reflects a 2025 demerger of
# Tata Motors into separate commercial/passenger-vehicle listings - double
# check this symbol against your broker/NSE before relying on it.
NIFTY_50 = [
    "ADANIENT", "ADANIPORTS", "APOLLOHOSP", "ASIANPAINT", "AXISBANK",
    "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV", "BEL", "BHARTIARTL",
    "CIPLA", "COALINDIA", "DRREDDY", "EICHERMOT", "ETERNAL",
    "GRASIM", "HCLTECH", "HDFCBANK", "HDFCLIFE", "HINDALCO",
    "HINDUNILVR", "ICICIBANK", "INDIGO", "INFY", "ITC",
    "JIOFIN", "JSWSTEEL", "KOTAKBANK", "LT", "M&M",
    "MARUTI", "MAXHEALTH", "NESTLEIND", "NTPC", "ONGC",
    "POWERGRID", "RELIANCE", "SBILIFE", "SHRIRAMFIN", "SBIN",
    "SUNPHARMA", "TCS", "TATACONSUM", "TMPV", "TATASTEEL",
    "TECHM", "TITAN", "TRENT", "ULTRACEMCO", "WIPRO",
]

# A couple of these (post-demerger entities) are less certain than the
# rest - verify before relying on them: TATAMOTORS (Tata Motors, post
# commercial/passenger vehicle split), TATACAPITAL, SIEMENS Energy spinoff.
# NOTE: 49, not 50 - "Siemens Energy" (source symbol uncertain, possibly
# ENRIN post-listing) was deliberately dropped rather than guessed. Add it
# yourself once confirmed, or just use Custom list / Upload CSV.
NIFTY_NEXT_50_AS_OF = "2026-04-01"
NIFTY_NEXT_50 = [
    "ABB", "ADANIENSOL", "ADANIGREEN", "ADANIPOWER", "AMBUJACEM",
    "BAJAJHLDNG", "BANKBARODA", "BPCL", "BRITANNIA", "BOSCHLTD",
    "CANBK", "CGPOWER", "CHOLAFIN", "CUMMINSIND", "DIVISLAB",
    "DLF", "DMART", "GAIL", "GODREJCP", "HDFCAMC",
    "HAL", "HINDZINC", "HYUNDAI", "INDHOTEL", "IOC",
    "IRFC", "JINDALSTEL", "LODHA", "LTIM", "MAZDOCK",
    "MUTHOOTFIN", "PIDILITIND", "PFC", "PNB", "RECLTD",
    "MOTHERSON", "SHREECEM", "SIEMENS", "SOLARINDS", "TATACAPITAL",
    "TATAMOTORS", "TATAPOWER", "TORNTPHARM", "TVSMOTOR", "UNIONBANK",
    "UNITDSPR", "VBL", "VEDL", "ZYDUSLIFE",
]

NIFTY_MIDCAP_150_AS_OF = "2026-04-01"
NIFTY_MIDCAP_150 = [
    "3MINDIA", "ABCAPITAL", "ABBOTINDIA", "ACC", "AIAENG", "AJANTPHARM", 
    "ALKEM", "APLLTD", "APARINDS", "APLAPOLLO", "APOLLOTYRE", "ASHOKLEY", 
    "ASTRAL", "ATGL", "AUROPHARMA", "BALKRISIND", "BANDHANBNK", "BANKINDIA", 
    "BHEL", "BHARATFORG", "BHRATWIRE", "BHARTIHEXA", "BIOCON", "BLUESTARCO", 
    "BSE", "COFORGE", "COLPAL", "CONCOR", "COROMANDEL", "CRISIL", 
    "CUMMINSIND", "DALBHARAT", "DEEPAKNTR", "DELHIVERY", "DIXON", "EMMBI", 
    "ESCORTS", "EXIDEIND", "FEDERALBNK", "FORTIS", "GLAXO", "GLENMARK", 
    "GMRINFRA", "GODREJIND", "GODREJPROP", "GRANULES", "GUJGASLTD", "HAVELLS", 
    "HEROMOTOCO", "HINDPETRO", "HONAUT", "HUDCO", "ICICIGI", "ICICIPRULI", 
    "IDFCFIRSTB", "INDIAMART", "INDIANB", "INDUSINDBK", "INDUSTOWER", "INFIBEAM", 
    "IREDA", "IRCTC", "IRFC", "ITDC", "JINDALSTEL", "JUBLFOOD", "KALYANKJIL", 
    "KEI", "KPITTECH", "KPRMILL", "LALPATHLAB", "LAURUSLABS", "LICHSGFIN", 
    "LINDEINDIA", "LUPIN", "MAHABANK", "MARICO", "MASTEK", "MAXFIN", 
    "MCX", "MEDANTA", "METROPOLIS", "MPHASIS", "MRF", "NATIONALUM", 
    "NAVINFLUOR", "NFL", "NHPC", "NIACL", "NIPPONLIFE", "NLCINDIA", 
    "NMDC", "NOCIL", "OBEROIRLTY", "OFSS", "OIL", "PAGEIND", 
    "PATANJALI", "PAYTM", "PERSISTENT", "PETRONET", "PHOENIXLTD", "PIIND", 
    "PNBHOUSING", "POLYCAB", "POLYMED", "POONAWALLA", "POWERINDIA", "PRESTIGE", 
    "RADICO", "RAMCOCEM", "RATNAMANI", "RBLBANK", "RELAXO", "RVNL", 
    "SAIL", "SANSERA", "SBICARD", "SCHAEFFLER", "SHREECEM", "SJVN", 
    "SKFINDIA", "SONACOMS", "SRF", "STARHEALTH", "SUNDARMFIN", "SUNTECK", 
    "SUPREMEIND", "SUZLON", "SWIGGY", "SYNGENE", "TATACOMM", "TATAELXSI", 
    "TATAINVEST", "TEJASNET", "THERMAX", "TIMKEN", "TORNTPOWER", "TRIDENT", 
    "TRITURBINE", "TIINDIA", "UBL", "UNOMINDA", "UPL", "VGUARD", 
    "VIPIND", "VOLTAS", "WHIRLPOOL", "WOCKPHARMA", "YESBANK", "ZEEL", 
    "ZENSARTECH"
]

NIFTY_SMALLCAP_250_AS_OF = "2026-04-01"
NIFTY_SMALLCAP_250 = [
    "AARTIIND", "AAVAS", "ABFRL", "ACME", "AEGISLOG", "ALOKINDS", 
    "AMARAJABAT", "ANANDRATHI", "ANGELONE", "ANUPAMRAS", "APLLTD", "APTUS", 
    "ARMANFIN", "ASAINGLASS", "ASTERDM", "ATUL", "AVANTIFEED", "BALAMINES", 
    "BALRAMCHIN", "BATAINDIA", "BAYERCROP", "BEML", "BIKAJI", "BIRLACORPN", 
    "BLS", "BLUESTARCO", "BOMDYEING", "BORORENEW", "BRIGADE", "CAMPUS", 
    "CANFINHOME", "CAPLIPOINT", "CASTROLIND", "CEATLTD", "CEINFO", "CENTURYTEX", 
    "CERA", "CESC", "CHALET", "CHAMBLFERT", "CHOLAHLDNG", "CIEINDIA", 
    "CLEAN", "COCOCHOLA", "COFORGE", "CONCORDBIO", "CRAFTSMAN", "CREDITACC", 
    "CROMPTON", "CSBBANK", "CYIENT", "DATAPATTERNS", "DCAL", "DCBBANK", 
    "DCMSHRIRAM", "DEEPAKFERT", "DELTACORP", "DHANUKA", "DOMS", "EASEMYTRIP", 
    "EDELWEISS", "EIDPARRY", "EIHOTEL", "ELGIEQUIP", "EMAMILTD", "ENDURANCE", 
    "ENGINERSIN", "EPL", "ERIS", "ESCORTS", "EXIDEIND", "FDC", 
    "FEDERALBNK", "FINCABLES", "FINEORG", "FINPIPE", "FIVESTAR", "FLUOROCHEM", 
    "FORCEMOT", "FORTIS", "GABRIEL", "GAEL", "GARFIBRES", "GDL", 
    "GEPIL", "GESHIP", "GHCL", "GICRE", "GILLETTE", "GLENMARK", 
    "GLS", "GMDCLTD", "GMMPFAUDL", "GMRINFRA", "GNFC", "GOCOLORS", 
    "GODFRYPHLP", "GODREJAGRO", "GRANULES", "GRAPHITE", "GRINFRA", "GRSE", 
    "GSFC", "GSPL", "GVKPIL", "HAPPYFORGE", "HATHWAY", "HBLPOWER", 
    "HCC", "HFCL", "HGINFRA", "HIKAL", "HINDCOPPER", "HINDWARE", 
    "HOMEFIRST", "HONASA", "HUDCO", "IBREALEST", "IBULHSGFIN", "ICIL", 
    "IDBI", "IDFC", "IFCI", "IIFL", "IKIO", "INDIACEM", 
    "INDIAGLYCO", "INDIAMART", "INDIGO", "INDIGOPNTS", "INFIBEAM", "INOXGREEN", 
    "INOXWIND", "INTELLECT", "IONEXCHANG", "IPCALAB", "IRB", "IRCON", 
    "IEX", "ISGEC", "ITI", "J&KBANK", "JAICORPLTD", "JAMNAAUTO", 
    "JBCHEPHARM", "JESSOP", "JINDALSAW", "JINDWORLD", "JKCEMENT", "JKLAC", 
    "JKTYRE", "JMFINANCIL", "JSL", "JUBLINGREA", "JUBLPHARMA", "JUPITERWAG", 
    "JUSTDIAL", "JYOTICNC", "KAJARIACER", "KALPATAFR", "KALYANKJIL", "KARURVYSYA", 
    "KAYNES", "KEC", "KFINTECH", "KIMS", "KIRLOSENG", "KNRCON", 
    "KOPRAN", "KPITTECH", "KPRMILL", "KRBL", "KREBSBIO", "KSB", 
    "KSCL", "KTKBANK", "LALPATHLAB", "LATENTVIEW", "LAURUSLABS", "LEMONTREE", 
    "LINCOLN", "LLOYDSME", "LMF", "LOKESHMACH", "LTFOODS", "LUXIND", 
    "LXCHEM", "MAHSEAMLES", "MAHSCOOTER", "MAHABANK", "MAHLOG", "MANAPPURAM", 
    "MANGCHEFER", "MAPMYINDIA", "MARATHON", "MARKSANS", "MASFIN", "MEDANTA", 
    "MEDIPLUS", "METROPOLIS", "MHRIL", "MIDHANI", "MINDAIND", "MINDACORP", 
    "MMTC", "MOIL", "MONTECARLO", "MOTILALOFS", "MRPL", "MSUMI", 
    "MTARTECH", "MUTHOOTMF", "NATCOPHARM", "NAVA", "NAZARA", "NBCC", 
    "NCC", "NETWEB", "NEULANDLAB", "NEWGEN", "NHPC", "NIACL", 
    "NILKAMAL", "NIPPONLIFE", "NLCINDIA", "NMDCSTEEL", "NOCIL", "NRELEC", 
    "NUCLEUS", "NUVAMA", "NUVOCO", "OLAELEC", "OLECTRA", "OMAXE", 
    "ONMOBILE", "ORIENTCEM", "ORIENTELEC", "PARADEEP", "PARAS", "PCBL", 
    "PFIZER", "PGELECTRO", "PHOENIXLTD", "PIRAMALPHY", "PNBHOUSING", "POLYMED", 
    "POLYNM", "POONAWALLA", "PPL", "PRACHIN", "PRAJIND", "PRESTIGE", 
    "PRICOLLTD", "PRINCEPIPE", "PRIVISCL", "PTC", "PVRINOX", "QUESS", 
    "QUICKHEAL", "RADICO", "RAILTEL", "RAIN", "RAINBOW", "RALLIS", 
    "RAMCOCEM", "RAMCOIND", "RAMKY", "RATNAMANI", "RAYMOND", "RBLBANK", 
    "RCF", "RECKITT", "REDINGTON", "RELAXO", "RELIANCEP", "RELINFRA", 
    "RENUKA", "RHI", "RITES", "RKFORGE", "ROLEXRINGS", "ROUTE", 
    "RRKABEL", "RSWM", "RVNL", "SADBHAV", "SAFARI", "SAGILITY", 
    "SAIL", "SAILIFE", "SAMHI", "SANSERA", "SAPPHIRE", "SARDAEN", 
    "SAREGAMA", "SATINGLST", "SBFC", "SCHNEIDER", "SCI", "SFL", 
    "SHAKTIPUMP", "SHALBY", "SHANTI", "SHARDAMOTR", "SHOPERSTOP", "SHREERAM", 
    "SHYAMMETL", "SIGNATURE", "SILVER", "SJVN", "SKFINDIA", "SKIPPER", 
    "SMSPHARMA", "SOBHA", "SOLARA", "SONACOMS", "SONATSOFTW", "SPANDANA", 
    "SPARC", "SRF", "STARHEALTH", "STERTOOLS", "STLTECH", "SUDARSCHEM", 
    "SUMICHEM", "SUNCLAY", "SUNTECK", "SUNTV", "SUPRAJIT", "SUPREMEIND", 
    "SUPREMEPET", "SUVENPHAR", "SUZLON", "SWANENERGY", "SYNGENE", "SYRMA", 
    "TAJGVK", "TANLA", "TASTYBITE", "TATACHEM", "TATACOFFEE", "TATAELXSI", 
    "TATAMETAL", "TATATECH", "TTML", "TBOTEK", "TECHNOE", 
    "TEGA", "TEJASNET", "TEXRAIL", "THANGAMAYL", "THERMAX", "THYROCARE", 
    "TIIL", "TIMETECH", "TIMKEN", "TITAGARH", "TNL", "TRIDENT", 
    "TRITURBINE", "TTKPRESTIG", "TV18BRDCST", "UCOBANK", "UFLEX", "UJJIVANSFB", 
    "ULTRACEMCO", "UNICHEMLAB", "UNIONBANK", "UNIPARTS", "UNOMINDA", "UPGRADE", 
    "USHAMART", "UTIAMC", "VAIBHAVGBL", "VAKRANGEE", "VALIANTORG", "VAMSHI", 
    "VARDHMAN", "VARROC", "VBL", "VENKEYS", "VESUVIUS", "VGUARD", 
    "VIJAYA", "VINATIORGA", "VIPIND", "VIPULLTD", "VISHNU", "VOLTAMP", 
    "VRLLOG", "VSTIND", "VTL", "WABAG", "WELCORP", "WELSPUNLIV", 
    "WESTLIFE", "WHIRLPOOL", "WIPRO", "WOCKPHARMA", "XCHANGING", "YESBANK", 
    "ZEEL", "ZENSARTECH", "ZENTEC", "ZFCVINDIA", "ZUARI", "ZYDUSWELL"
]


PRESETS = {
    "NIFTY 50": (NIFTY_50, NIFTY_50_AS_OF),
    "NIFTY Next 50": (NIFTY_NEXT_50, NIFTY_NEXT_50_AS_OF),
    "NIFTY 100": (NIFTY_50 + NIFTY_NEXT_50, f"{NIFTY_50_AS_OF} / {NIFTY_NEXT_50_AS_OF}"),
    "NIFTY Midcap 150": (NIFTY_MIDCAP_150, NIFTY_MIDCAP_150_AS_OF),
    "NIFTY Smallcap 250": (NIFTY_SMALLCAP_250, NIFTY_SMALLCAP_250_AS_OF),
}

# Company names for the sidebar's search-by-name ticker picker - best-effort
# for search/display convenience only, not guaranteed exact-legal-name
# accuracy (a few post-demerger/rename entities are genuinely ambiguous,
# see the NOTEs above). If a name looks wrong, the symbol itself is what
# actually drives the analysis - use "Type ticker directly" for precision.
COMPANY_NAMES = {
    "ADANIENT": "Adani Enterprises", "ADANIPORTS": "Adani Ports & SEZ",
    "APOLLOHOSP": "Apollo Hospitals", "ASIANPAINT": "Asian Paints",
    "AXISBANK": "Axis Bank", "BAJAJ-AUTO": "Bajaj Auto",
    "BAJFINANCE": "Bajaj Finance", "BAJAJFINSV": "Bajaj Finserv",
    "BEL": "Bharat Electronics", "BHARTIARTL": "Bharti Airtel",
    "CIPLA": "Cipla", "COALINDIA": "Coal India",
    "DRREDDY": "Dr Reddy's Laboratories", "EICHERMOT": "Eicher Motors",
    "ETERNAL": "Eternal (Zomato)", "GRASIM": "Grasim Industries",
    "HCLTECH": "HCL Technologies", "HDFCBANK": "HDFC Bank",
    "HDFCLIFE": "HDFC Life Insurance", "HINDALCO": "Hindalco Industries",
    "HINDUNILVR": "Hindustan Unilever", "ICICIBANK": "ICICI Bank",
    "INDIGO": "InterGlobe Aviation (IndiGo)", "INFY": "Infosys",
    "ITC": "ITC Limited", "JIOFIN": "Jio Financial Services",
    "JSWSTEEL": "JSW Steel", "KOTAKBANK": "Kotak Mahindra Bank",
    "LT": "Larsen & Toubro", "M&M": "Mahindra & Mahindra",
    "MARUTI": "Maruti Suzuki India", "MAXHEALTH": "Max Healthcare",
    "NESTLEIND": "Nestle India", "NTPC": "NTPC Limited",
    "ONGC": "Oil & Natural Gas Corporation", "POWERGRID": "Power Grid Corporation",
    "RELIANCE": "Reliance Industries", "SBILIFE": "SBI Life Insurance",
    "SHRIRAMFIN": "Shriram Finance", "SBIN": "State Bank of India",
    "SUNPHARMA": "Sun Pharmaceutical Industries", "TCS": "Tata Consultancy Services",
    "TATACONSUM": "Tata Consumer Products", "TMPV": "Tata Motors Passenger Vehicles",
    "TATASTEEL": "Tata Steel", "TECHM": "Tech Mahindra",
    "TITAN": "Titan Company", "TRENT": "Trent Limited",
    "ULTRACEMCO": "UltraTech Cement", "WIPRO": "Wipro",
    "ABB": "ABB India", "ADANIENSOL": "Adani Energy Solutions",
    "ADANIGREEN": "Adani Green Energy", "ADANIPOWER": "Adani Power",
    "AMBUJACEM": "Ambuja Cements", "BAJAJHLDNG": "Bajaj Holdings & Investment",
    "BANKBARODA": "Bank of Baroda", "BPCL": "Bharat Petroleum",
    "BRITANNIA": "Britannia Industries", "BOSCHLTD": "Bosch Limited",
    "CANBK": "Canara Bank", "CGPOWER": "CG Power & Industrial Solutions",
    "CHOLAFIN": "Cholamandalam Investment & Finance", "CUMMINSIND": "Cummins India",
    "DIVISLAB": "Divi's Laboratories", "DLF": "DLF Limited",
    "DMART": "Avenue Supermarts (DMart)", "GAIL": "GAIL India",
    "GODREJCP": "Godrej Consumer Products", "HDFCAMC": "HDFC Asset Management",
    "HAL": "Hindustan Aeronautics", "HINDZINC": "Hindustan Zinc",
    "HYUNDAI": "Hyundai Motor India", "INDHOTEL": "Indian Hotels Company",
    "IOC": "Indian Oil Corporation", "IRFC": "Indian Railway Finance Corporation",
    "JINDALSTEL": "Jindal Steel & Power", "LODHA": "Macrotech Developers (Lodha)",
    "LTIM": "LTIMindtree", "MAZDOCK": "Mazagon Dock Shipbuilders",
    "MUTHOOTFIN": "Muthoot Finance", "PIDILITIND": "Pidilite Industries",
    "PFC": "Power Finance Corporation", "PNB": "Punjab National Bank",
    "RECLTD": "REC Limited", "MOTHERSON": "Samvardhana Motherson International",
    "SHREECEM": "Shree Cement", "SIEMENS": "Siemens Limited",
    "SOLARINDS": "Solar Industries India", "TATACAPITAL": "Tata Capital",
    "TATAMOTORS": "Tata Motors", "TATAPOWER": "Tata Power",
    "TORNTPHARM": "Torrent Pharmaceuticals", "TVSMOTOR": "TVS Motor Company",
    "UNIONBANK": "Union Bank of India", "UNITDSPR": "United Spirits",
    "VBL": "Varun Beverages", "VEDL": "Vedanta Limited",
    "ZYDUSLIFE": "Zydus Lifesciences",

    ## Nifty Midcap 150
    "3MINDIA": "3M India",
    "ABCAPITAL": "Aditya Birla Capital",
    "ABBOTINDIA": "Abbott India",
    "ACC": "ACC Limited",
    "AIAENG": "AIA Engineering",
    "AJANTPHARM": "Ajanta Pharma",
    "ALKEM": "Alkem Laboratories",
    "APLLTD": "Alembic Pharmaceuticals",
    "APARINDS": "Apar Industries",
    "APLAPOLLO": "APL Apollo Tubes",
    "APOLLOTYRE": "Apollo Tyres",
    "ASHOKLEY": "Ashok Leyland",
    "ASTRAL": "Astral Limited",
    "ATGL": "Adani Total Gas",
    "AUROPHARMA": "Aurobindo Pharma",
    "BALKRISIND": "Balkrishna Industries",
    "BANDHANBNK": "Bandhan Bank",
    "BANKINDIA": "Bank of India",
    "BHEL": "Bharat Heavy Electricals",
    "BHARATFORG": "Bharat Forge",
    "BHRATWIRE": "Bharat Wire Ropes",
    "BHARTIHEXA": "Bharti Hexacom",
    "BIOCON": "Biocon Limited",
    "BLUESTARCO": "Blue Star",
    "BSE": "BSE Limited",
    "COFORGE": "Coforge Limited",
    "COLPAL": "Colgate-Palmolive (India)",
    "CONCOR": "Container Corporation of India",
    "COROMANDEL": "Coromandel International",
    "CRISIL": "CRISIL Limited",
    "CUMMINSIND": "Cummins India",
    "DALBHARAT": "Dalmia Bharat",
    "DEEPAKNTR": "Deepak Nitrite",
    "DELHIVERY": "Delhivery Limited",
    "DIXON": "Dixon Technologies",
    "EMMBI": "Emmbi Industries",
    "ESCORTS": "Escorts Kubota",
    "EXIDEIND": "Exide Industries",
    "FEDERALBNK": "Federal Bank",
    "FORTIS": "Fortis Healthcare",
    "GLAXO": "GlaxoSmithKline Pharmaceuticals",
    "GLENMARK": "Glenmark Pharmaceuticals",
    "GMRINFRA": "GMR Airports Infrastructure",
    "GODREJIND": "Godrej Industries",
    "GODREJPROP": "Godrej Properties",
    "GRANULES": "Granules India",
    "GUJGASLTD": "Gujarat Gas",
    "HAVELLS": "Havells India",
    "HEROMOTOCO": "Hero MotoCorp",
    "HINDPETRO": "Hindustan Petroleum Corporation",
    "HONAUT": "Honeywell Automation India",
    "HUDCO": "Housing & Urban Development Corporation",
    "ICICIGI": "ICICI Lombard General Insurance",
    "ICICIPRULI": "ICICI Prudential Life Insurance",
    "IDFCFIRSTB": "IDFC First Bank",
    "INDIAMART": "IndiaMART InterMESH",
    "INDIANB": "Indian Bank",
    "INDUSINDBK": "IndusInd Bank",
    "INDUSTOWER": "Indus Towers",
    "INFIBEAM": "Infibeam Avenues",
    "IREDA": "Indian Renewable Energy Development Agency",
    "IRCTC": "Indian Railway Catering and Tourism Corporation",
    "IRFC": "Indian Railway Finance Corporation",
    "ITDC": "India Tourism Development Corporation",
    "JINDALSTEL": "Jindal Steel & Power",
    "JUBLFOOD": "Jubilant FoodWorks",
    "KALYANKJIL": "Kalyan Jewellers India",
    "KEI": "KEI Industries",
    "KPITTECH": "KPIT Technologies",
    "KPRMILL": "KPR Mill",
    "LALPATHLAB": "Dr. Lal PathLabs",
    "LAURUSLABS": "Laurus Labs",
    "LICHSGFIN": "LIC Housing Finance",
    "LINDEINDIA": "Linde India",
    "LUPIN": "L Lupin Limited",
    "MAHABANK": "Bank of Maharashtra",
    "MARICO": "Marico Limited",
    "MASTEK": "Mastek Limited",
    "MAXFIN": "Max Financial Services",
    "MCX": "Multi Commodity Exchange of India",
    "MEDANTA": "Global Health (Medanta)",
    "METROPOLIS": "Metropolis Healthcare",
    "MPHASIS": "Mphasis Limited",
    "MRF": "MRF Limited",
    "NATIONALUM": "National Aluminium Company",
    "NAVINFLUOR": "Navin Fluorine International",
    "NFL": "National Fertilizers",
    "NHPC": "NHPC Limited",
    "NIACL": "The New India Assurance Company",
    "NIPPONLIFE": "Nippon Life India Asset Management",
    "NLCINDIA": "NLC India",
    "NMDC": "NMDC Limited",
    "NOCIL": "NOCIL Limited",
    "OBEROIRLTY": "Oberoi Realty",
    "OFSS": "Oracle Financial Services Software",
    "OIL": "Oil India Limited",
    "PAGEIND": "Page Industries",
    "PATANJALI": "Patanjali Foods",
    "PAYTM": "One 97 Communications (Paytm)",
    "PERSISTENT": "Persistent Systems",
    "PETRONET": "Petronet LNG",
    "PHOENIXLTD": "The Phoenix Mills",
    "PIIND": "PI Industries",
    "PNBHOUSING": "PNB Housing Finance",
    "POLYCAB": "Polycab India",
    "POLYMED": "Poly Medicure",
    "POONAWALLA": "Poonawalla Fincorp",
    "POWERINDIA": "Hitachi Energy India",
    "PRESTIGE": "Prestige Estates Projects",
    "RADICO": "Radico Khaitan",
    "RAMCOCEM": "The Ramco Cements",
    "RATNAMANI": "Ratnamani Metals & Tubes",
    "RBLBANK": "RBL Bank",
    "RELAXO": "Relaxo Footwears",
    "RVNL": "Rail Vikas Nigam",
    "SAIL": "Steel Authority of India",
    "SANSERA": "Sansera Engineering",
    "SBICARD": "SBI Cards and Payment Services",
    "SCHAEFFLER": "Schaeffler India",
    "SHREECEM": "Shree Cement",
    "SJVN": "SJVN Limited",
    "SKFINDIA": "SKF India",
    "SONACOMS": "Sona BLW Precision Forgings",
    "SRF": "SRF Limited",
    "STARHEALTH": "Star Health and Allied Insurance",
    "SUNDARMFIN": "Sundaram Finance",
    "SUNTECK": "Sunteck Realty",
    "SUPREMEIND": "Supreme Industries",
    "SUZLON": "Suzlon Energy",
    "SWIGGY": "Swiggy Limited",
    "SYNGENE": "Syngene International",
    "TATACOMM": "Tata Communications",
    "TATAELXSI": "Tata Elxsi",
    "TATAINVEST": "Tata Investment Corporation",
    "TEJASNET": "Tejas Networks",
    "THERMAX": "Thermax Limited",
    "TIMKEN": "Timken India",
    "TORNTPOWER": "Torrent Power",
    "TRIDENT": "Trident Limited",
    "TRITURBINE": "Triveni Turbine",
    "TIINDIA": "Tube Investments of India",
    "UBL": "United Breweries",
    "UNOMINDA": "Uno Minda",
    "UPL": "UPL Limited",
    "VGUARD": "V-Guard Industries",
    "VIPIND": "VIP Industries",
    "VOLTAS": "Voltas Limited",
    "WHIRLPOOL": "Whirlpool of India",
    "WOCKPHARMA": "Wockhardt Limited",
    "YESBANK": "Yes Bank",
    "ZEEL": "Zee Entertainment Enterprises",
    "ZENSARTECH": "Zensar Technologies",

    ## Nifty Small Cap 250
    "AARTIIND": "Aarti Industries",
    "AAVAS": "Aavas Financiers",
    "ABFRL": "Aditya Birla Fashion and Retail",
    "ACME": "ACME Solar Holdings",
    "AEGISLOG": "Aegis Logistics",
    "ALOKINDS": "Alok Industries",
    "AMARAJABAT": "Amara Raja Energy & Mobility",
    "ANANDRATHI": "Anand Rathi Wealth",
    "ANGELONE": "Angel One",
    "ANUPAMRAS": "Anupam Rasayan India",
    "APLLTD": "Alembic Pharmaceuticals",
    "APTUS": "Aptus Value Housing Finance",
    "ARMANFIN": "Arman Financial Services",
    "ASAINGLASS": "Asahi India Glass",
    "ASTERDM": "Aster DM Healthcare",
    "ATUL": "Atul Limited",
    "AVANTIFEED": "Avanti Feeds",
    "BALAMINES": "Balaji Amines",
    "BALRAMCHIN": "Balrampur Chini Mills",
    "BATAINDIA": "Bata India",
    "BAYERCROP": "Bayer CropScience",
    "BEML": "BEML Limited",
    "BIKAJI": "Bikaji Foods International",
    "BIRLACORPN": "Birla Corporation",
    "BLS": "BLS International Services",
    "BLUESTARCO": "Blue Star Limited",
    "BOMDYEING": "Bombay Dyeing & Mfg",
    "BORORENEW": "Borosil Renewables",
    "BRIGADE": "Brigade Enterprises",
    "CAMPUS": "Campus Activewear",
    "CANFINHOME": "Can Fin Homes",
    "CAPLIPOINT": "Caplin Point Laboratories",
    "CASTROLIND": "Castrol India",
    "CEATLTD": "CEAT Limited",
    "CEINFO": "CE Info Systems (MapmyIndia)",
    "CENTURYTEX": "Century Textiles & Industries",
    "CERA": "Cera Sanitaryware",
    "CESC": "CESC Limited",
    "CHALET": "Chalet Hotels",
    "CHAMBLFERT": "Chambal Fertilisers & Chemicals",
    "CHOLAHLDNG": "Cholamandalam Financial Holdings",
    "CIEINDIA": "CIE Automotive India",
    "CLEAN": "Clean Science & Technology",
    "COCOCHOLA": "Coromandel Engineering",
    "COFORGE": "Coforge Limited",
    "CONCORDBIO": "Concord Biotech",
    "CRAFTSMAN": "Craftsman Automation",
    "CREDITACC": "CreditAccess Grameen",
    "CROMPTON": "Crompton Greaves Consumer Electricals",
    "CSBBANK": "CSB Bank",
    "CYIENT": "Cyient Limited",
    "DATAPATTERNS": "Data Patterns (India)",
    "DCAL": "Dishman Carbogen Amcis",
    "DCBBANK": "DCB Bank",
    "DCMSHRIRAM": "DCM Shriram",
    "DEEPAKFERT": "Deepak Fertilisers & Petrochemicals",
    "DELTACORP": "Delta Corp",
    "DHANUKA": "Dhanuka Agritech",
    "DOMS": "DOMS Industries",
    "EASEMYTRIP": "Easy Trip Planners",
    "EDELWEISS": "Edelweiss Financial Services",
    "EIDPARRY": "E.I.D. - Parry (India)",
    "EIHOTEL": "EIH Limited (Oberoi Hotels)",
    "ELGIEQUIP": "Elgi Equipments",
    "EMAMILTD": "Emami Limited",
    "ENDURANCE": "Endurance Technologies",
    "ENGINERSIN": "Engineers India",
    "EPL": "EPL Limited",
    "ERIS": "Eris Lifesciences",
    "ESCORTS": "Escorts Kubota",
    "EXIDEIND": "Exide Industries",
    "FDC": "FDC Limited",
    "FEDERALBNK": "Federal Bank",
    "FINCABLES": "Finolex Cables",
    "FINEORG": "Fine Organic Industries",
    "FINPIPE": "Finolex Industries",
    "FIVESTAR": "Five-Star Business Finance",
    "FLUOROCHEM": "Gujarat Fluorochemicals",
    "FORCEMOT": "Force Motors",
    "FORTIS": "Fortis Healthcare",
    "GABRIEL": "Gabriel India",
    "GAEL": "Gujarat Ambuja Exports",
    "GARFIBRES": "Garware Technical Fibres",
    "GDL": "Gateway Distriparks",
    "GEPIL": "GE Power India",
    "GESHIP": "Great Eastern Shipping Company",
    "GHCL": "GHCL Limited",
    "GICRE": "General Insurance Corporation of India",
    "GILLETTE": "Gillette India",
    "GLENMARK": "Glenmark Pharmaceuticals",
    "GLS": "Glenmark Life Sciences",
    "GMDCLTD": "Gujarat Mineral Development Corporation",
    "GMMPFAUDL": "GMM Pfaudler",
    "GMRINFRA": "GMR Airports Infrastructure",
    "GNFC": "Gujarat Narmada Valley Fertilizers",
    "GOCOLORS": "Go Fashion (India)",
    "GODFRYPHLP": "Godfrey Phillips India",
    "GODREJAGRO": "Godrej Agrovet",
    "GRANULES": "Granules India",
    "GRAPHITE": "Graphite India",
    "GRINFRA": "G R Infraprojects",
    "GRSE": "Garden Reach Shipbuilders & Engineers",
    "GSFC": "Gujarat State Fertilizers & Chemicals",
    "GSPL": "Gujarat State Petronet",
    "GVKPIL": "GVK Power & Infrastructure",
    "HAPPYFORGE": "Happy Forgings",
    "HATHWAY": "Hathway Cable & Datacom",
    "HBLPOWER": "HBL Power Systems",
    "HCC": "Hindustan Construction Company",
    "HFCL": "HFCL Limited",
    "HGINFRA": "H.G. Infra Engineering",
    "HIKAL": "Hikal Limited",
    "HINDCOPPER": "Hindustan Copper",
    "HINDWARE": "Hindware Home Innovation",
    "HOMEFIRST": "Home First Finance Company",
    "HONASA": "Honasa Consumer (Mamaearth)",
    "HUDCO": "Housing & Urban Development Corporation",
    "IBREALEST": "Indiabulls Real Estate",
    "IBULHSGFIN": "SAMHI Hotels (formerly Indiabulls Housing)",
    "ICIL": "Indo Count Industries",
    "IDBI": "IDBI Bank",
    "IDFC": "IDFC Limited",
    "IFCI": "IFCI Limited",
    "IIFL": "IIFL Finance",
    "IKIO": "IKIO Lighting",
    "INDIACEM": "The India Cements",
    "INDIAGLYCO": "India Glycols",
    "INDIAMART": "IndiaMART InterMESH",
    "INDIGO": "InterGlobe Aviation",
    "INDIGOPNTS": "Indigo Paints",
    "INFIBEAM": "Infibeam Avenues",
    "INOXGREEN": "Inox Green Energy Services",
    "INOXWIND": "Inox Wind",
    "INTELLECT": "Intellect Design Arena",
    "IONEXCHANG": "Ion Exchange (India)",
    "IPCALAB": "IPCA Laboratories",
    "IRB": "IRB Infrastructure Developers",
    "IRCON": "Ircon International",
    "IEX": "Indian Energy Exchange",
    "ISGEC": "Isgec Heavy Engineering",
    "ITI": "ITI Limited",
    "J&KBANK": "The Jammu & Kashmir Bank",
    "JAICORPLTD": "Jai Corp",
    "JAMNAAUTO": "Jamna Auto Industries",
    "JBCHEPHARM": "J.B. Chemicals & Pharmaceuticals",
    "JESSOP": "Jessop & Company",
    "JINDALSAW": "Jindal Saw",
    "JINDWORLD": "Jindal Worldwide",
    "JKCEMENT": "JK Cement",
    "JKLAC": "JK Lakshmi Cement",
    "JKTYRE": "JK Tyre & Industries",
    "JMFINANCIL": "JM Financial",
    "JSL": "Jindal Stainless",
    "JUBLINGREA": "Jubilant Ingrevia",
    "JUBLPHARMA": "Jubilant Pharmova",
    "JUPITERWAG": "Jupiter Wagons",
    "JUSTDIAL": "Just Dial",
    "JYOTICNC": "Jyoti CNC Automation",
    "KAJARIACER": "Kajaria Ceramics",
    "KALPATAFR": "Kalpataru Projects International",
    "KALYANKJIL": "Kalyan Jewellers India",
    "KARURVYSYA": "Karur Vysya Bank",
    "KAYNES": "Kaynes Technology India",
    "KEC": "KEC International",
    "KFINTECH": "KFin Technologies",
    "KIMS": "Krishna Institute of Medical Sciences",
    "KIRLOSENG": "Kirloskar Oil Engines",
    "KNRCON": "KNR Constructions",
    "KOPRAN": "Kopran Limited",
    "KPITTECH": "KPIT Technologies",
    "KPRMILL": "KPR Mill",
    "KRBL": "KRBL Limited",
    "KREBSBIO": "Krebs Biochemicals & Industries",
    "KSB": "KSB Limited",
    "KSCL": "Kaveri Seed Company",
    "KTKBANK": "The Karnataka Bank",
    "LALPATHLAB": "Dr. Lal PathLabs",
    "LATENTVIEW": "Latent View Analytics",
    "LAURUSLABS": "Laurus Labs",
    "LEMONTREE": "Lemon Tree Hotels",
    "LINCOLN": "Lincoln Pharmaceuticals",
    "LLOYDSME": "Lloyds Metals & Energy",
    "LMF": "Landmark Cars",
    "LOKESHMACH": "Lokesh Machines",
    "LTFOODS": "LT Foods (Daawat)",
    "LUXIND": "Lux Industries",
    "LXCHEM": "Laxmi Organic Industries",
    "MAHSEAMLES": "Maharashtra Seamless",
    "MAHSCOOTER": "Maharashtra Scooters",
    "MAHABANK": "Bank of Maharashtra",
    "MAHLOG": "Mahindra Logistics",
    "MANAPPURAM": "Manappuram Finance",
    "MANGCHEFER": "Mangalore Chemicals & Fertilizers",
    "MAPMYINDIA": "C.E. Info Systems",
    "MARATHON": "Marathon Nextgen Realty",
    "MARKSANS": "Marksans Pharma",
    "MASFIN": "MAS Financial Services",
    "MEDANTA": "Global Health (Medanta)",
    "MEDIPLUS": "Medplus Health Services",
    "METROPOLIS": "Metropolis Healthcare",
    "MHRIL": "Mahindra Holidays & Resorts",
    "MIDHANI": "Mishra Dhatu Nigam",
    "MINDAIND": "Uno Minda (formerly Minda Industries)",
    "MINDACORP": "Minda Corporation",
    "MMTC": "MMTC Limited",
    "MOIL": "MOIL Limited",
    "MONTECARLO": "Monte Carlo Fashions",
    "MOTILALOFS": "Motilal Oswal Financial Services",
    "MRPL": "Mangalore Refinery & Petrochemicals",
    "MSUMI": "Motherson Sumi Wiring India",
    "MTARTECH": "MTAR Technologies",
    "MUTHOOTMF": "Muthoot Microfin",
    "NATCOPHARM": "Natco Pharma",
    "NAVA": "Nava Limited",
    "NAZARA": "Nazara Technologies",
    "NBCC": "NBCC (India)",
    "NCC": "NCC Limited",
    "NETWEB": "Netweb Technologies India",
    "NEULANDLAB": "Neuland Laboratories",
    "NEWGEN": "Newgen Software Technologies",
    "NHPC": "NHPC Limited",
    "NIACL": "The New India Assurance Company",
    "NILKAMAL": "Nilkamal Limited",
    "NIPPONLIFE": "Nippon Life India Asset Management",
    "NLCINDIA": "NLC India",
    "NMDCSTEEL": "NMDC Steel",
    "NOCIL": "NOCIL Limited",
    "NRELEC": "Nava Bharat Ventures",
    "NUCLEUS": "Nucleus Software Exports",
    "NUVAMA": "Nuvama Wealth Management",
    "NUVOCO": "Nuvoco Vistas Corporation",
    "OLAELEC": "Ola Electric Mobility",
    "OLECTRA": "Olectra Greentech",
    "OMAXE": "Omaxe Limited",
    "ONMOBILE": "OnMobile Global",
    "ORIENTCEM": "Orient Cement",
    "ORIENTELEC": "Orient Electric",
    "PARADEEP": "Paradeep Phosphates",
    "PARAS": "Paras Defence & Space Technologies",
    "PCBL": "PCBL Limited",
    "PFIZER": "Pfizer Limited",
    "PGELECTRO": "PG Electroplast",
    "PHOENIXLTD": "The Phoenix Mills",
    "PIRAMALPHY": "Piramal Pharma",
    "PNBHOUSING": "PNB Housing Finance",
    "POLYMED": "Poly Medicure",
    "POLYNM": "Polyplastics",
    "POONAWALLA": "Poonawalla Fincorp",
    "PPL": "Prakash Pipes",
    "PRACHIN": "Prakash Industries",
    "PRAJIND": "Praj Industries",
    "PRESTIGE": "Prestige Estates Projects",
    "PRICOLLTD": "Pricol Limited",
    "PRINCEPIPE": "Prince Pipes & Fittings",
    "PRIVISCL": "Privi Speciality Chemicals",
    "PTC": "PTC India",
    "PVRINOX": "PVR INOX Limited",
    "QUESS": "Quess Corp",
    "QUICKHEAL": "Quick Heal Technologies",
    "RADICO": "Radico Khaitan",

}


def search_universe() -> list:
    """
    (ticker, display_label) pairs for every NIFTY 50 + Next 50 constituent,
    sorted by company name - feeds the sidebar's search-by-name picker.
    """
    symbols = NIFTY_50 + NIFTY_NEXT_50 + NIFTY_MIDCAP_150 + NIFTY_SMALLCAP_250
    pairs = []
    for s in symbols:
        ticker = f"{s}.NS"
        name = COMPANY_NAMES.get(s, s)
        pairs.append((ticker, f"{name} ({ticker})"))
    return sorted(pairs, key=lambda pair: pair[1])


def get_ticker_list(preset_name: str) -> list:
    symbols, _ = PRESETS[preset_name]
    return [f"{s}.NS" for s in symbols]


def get_as_of(preset_name: str) -> str:
    _, as_of = PRESETS[preset_name]
    return as_of
