"""
smc_backend.py

This is your real backend (my_backend.py), library portion ONLY -
every function/class definition, UNCHANGED, up to (not including) the
Colab driver script that used to sit at the bottom of the notebook
export (drive.mount, live run_strategy_for_ticker() call, plots, etc.).
That driver code has been removed entirely, not just guarded, since none
of it is needed here - the Streamlit app drives everything through
data_access.py / zone_identification_multibase.py instead.

The only edits made to the code below (vs. your original file):
  - google.colab / matplotlib / seaborn / requests / scipy.signal.find_peaks
    imports wrapped in try/except ImportError - none of these are used by
    any function retained here (verified by grep), so this only prevents
    an import-time crash if an optional package isn't installed; it does
    not change any function's behavior.

Everything else - identity_zones_with_multibase, calculate_trade_score,
backtest_zones, run_risk_management_simulation, evaluate_strategy_metrics,
calculate_composite_score, run_strategy_for_ticker, plot_stock_zones(_monthly),
load_data, download_data, etc. - is verbatim.
"""
# -*- coding: utf-8 -*-
"""t16_detailed_anal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gax-ywa1NMGlephStZl2tfiX2csUgrE8
"""

# Imports

import yfinance as yf
import plotly.graph_objects as go
try:
    from scipy.signal import find_peaks  # unused by any function kept in this module
except ImportError:
    find_peaks = None
import pandas as pd
import numpy as np
try:
    import requests  # unused by any function kept in this module
except ImportError:
    requests = None
try:
    import matplotlib.pyplot as plt  # unused by any function kept in this module
except ImportError:
    plt = None
from datetime import date
import plotly.io as pio
import time
try:
    from google.colab import drive  # Colab-only; unused outside the excluded driver script
except ImportError:
    drive = None
import os
pio.renderers.default = 'colab'
try:
    import seaborn as sns  # unused by any function kept in this module
except ImportError:
    sns = None
from dataclasses import dataclass
try:
    from hmmlearn.hmm import GaussianHMM
    _HMM_AVAILABLE = True
except ImportError:
    _HMM_AVAILABLE = False

def load_data(drive_load_dir,tickers=None):
  # Check if the directory exists
  if not os.path.exists(drive_load_dir):
      print(f"Error: Directory not found at {drive_load_dir}. Please ensure the data was saved correctly.")
  else:
      print(f"Loading data from: {drive_load_dir}")

      # Initialize an empty dictionary to store the loaded data
      loaded_data_multi = {}
      all_files = os.listdir(drive_load_dir)

      if tickers is not None:
        all_files = [file for file in all_files if any(ticker.split('.')[0] in file for ticker in tickers)]

      # Iterate through files in the directory
      for filename in all_files:
          if filename.endswith('.csv'):
              # Extract ticker and interval from the filename
              parts = filename.replace('.csv', '').split('_')
              if len(parts) >= 2:
                  # Reconstruct original ticker (e.g., 'ABB_NS' -> 'ABB.NS')
                  ticker_parts = parts[:-1] # All parts except the last one are for the ticker
                  interval = parts[-1]   # The last part is the interval

                  if len(ticker_parts) == 2: # For tickers like 'ABB_NS'
                      ticker = f"{ticker_parts[0]}.{ticker_parts[1]}"
                  else: # For tickers like 'DMART' or 'ADANIENT'
                      ticker = "_".join(ticker_parts) # Join if there are multiple underscores in ticker name itself, although 'tickers' list seems to have only one dot
                      # A better way might be to store ticker and interval separately during saving, or use regex for more robust parsing

                  filepath = os.path.join(drive_load_dir, filename)
                  try:
                      df = pd.read_csv(filepath, index_col='Date', parse_dates=True)
                      if ticker not in loaded_data_multi:
                          loaded_data_multi[ticker] = {}
                      loaded_data_multi[ticker][interval] = df
                      #print(f"Loaded {ticker} data for interval {interval} from {filename}")
                  except Exception as e:
                      print(f"Error loading {filename}: {e}")

      print("\n--- All data loaded from Google Drive ---")
      return loaded_data_multi

def download_data(ticker, start_date="2023-01-01", end_date=None, intervals=["1d", "1wk", "1mo"]):
    """
    Downloads data for multiple intervals efficiently.
    Returns a dictionary: {interval: dataframe}
    """
    if end_date is None:
        end_date = date.today().strftime("%Y-%m-%d")

    results = {}

    for interval in intervals:
        try:
            # Small sleep to prevent rate limiting if calling in a large loop
            time.sleep(0.2)

            df = yf.download(ticker, start=start_date, end=end_date, interval=interval, progress=False, auto_adjust=True)

            if df.empty:
                print(f"No data found for {ticker} at {interval}")
                continue

            # Flatten multi-level columns if they exist
            if isinstance(df.columns, pd.MultiIndex):
                df.columns = [col[0] for col in df.columns]

            results[interval] = df
            #print(f"Successfully downloaded {ticker} at {interval} interval.")

        except Exception as e:
            print(f"Error downloading {ticker} at {interval}: {e}")

    return results

def resample_data(df, interval='1W'):
    """
    Resamples OHLCV data.
    Intervals: '1W' for Weekly, '1ME' for Monthly
    """
    resampled = df.resample(interval).agg({
        'Open': 'first',
        'High': 'max',
        'Low': 'min',
        'Close': 'last',
        'Volume': 'sum'
    })
    return resampled.dropna()

def infer_bar_frequency(index: pd.DatetimeIndex) -> str:
    """Infer whether the data is daily/weekly/monthly, purely for display -
    all downstream windows are expressed in BARS, not calendar days, so the
    algorithm itself is frequency-agnostic."""
    if len(index) < 3:
        return "unknown"
    median_days = np.median(np.diff(index.values).astype("timedelta64[D]").astype(int))
    if median_days <= 2:
        return "daily"
    if median_days <= 9:
        return "weekly"
    return "monthly"


# --------------------------------------------------------------------------- #
# 2. VOLATILITY LAYER - True Range / ATR computed in LOG space
# --------------------------------------------------------------------------- #
def compute_log_atr(df: pd.DataFrame, window: int = 14) -> pd.Series:
    """
    Log-space Average True Range. Using log(High), log(Low), log(Close)
    puts the noise floor in the same units as the log-slope from the Kalman
    filter (fractional move per bar), so no further division by price level
    is required downstream - this is what makes the SNR calculation
    scale-invariant across a stock's entire price history.
    """
    log_h, log_l, log_c = np.log(df["High"]), np.log(df["Low"]), np.log(df["Close"])
    prev_log_c = log_c.shift(1)

    tr = pd.concat(
        [(log_h - log_l), (log_h - prev_log_c).abs(), (log_l - prev_log_c).abs()],
        axis=1,
    ).max(axis=1)

    return tr.ewm(alpha=1.0 / window, min_periods=window, adjust=False).mean()


# --------------------------------------------------------------------------- #
# 3. KALMAN FILTER - LOG-PRICE LOCAL LINEAR TREND MODEL
# --------------------------------------------------------------------------- #
@dataclass
class KalmanTrendFilter:
    """
    State vector:      x_t = [log_level_t, log_slope_t]^T
    log_slope_t is the instantaneous fractional growth rate per bar - e.g.
    0.02 means the filtered price is currently growing ~2% per bar. This is
    directly comparable across any price level or point in the stock's
    history, which a raw-price slope is not.

    Transition:  x_t = F x_{t-1} + w_t,  F = [[1, 1], [0, 1]]
    Observation: z_t = H x_t + v_t,      H = [1, 0]   (we observe log-price)
    """

    level_process_var_ratio: float = 1e-3
    slope_process_var_ratio: float = 1e-3
    # Both ratios are expressed relative to the empirical variance of
    # bar-to-bar log-returns, so the filter self-calibrates to each
    # instrument's own volatility rather than needing per-ticker retuning.

    def run(self, log_prices: np.ndarray) -> pd.DataFrame:
        n = len(log_prices)
        diffs = np.diff(log_prices)
        base_var = np.var(diffs) if len(diffs) > 1 and np.var(diffs) > 0 else 1e-6

        R = base_var
        Q = np.array(
            [
                [base_var * self.level_process_var_ratio, 0.0],
                [0.0, base_var * self.slope_process_var_ratio],
            ]
        )
        F = np.array([[1.0, 1.0], [0.0, 1.0]])
        H = np.array([[1.0, 0.0]])

        x = np.array([log_prices[0], 0.0])
        P = np.diag([base_var, base_var])

        log_levels = np.empty(n)
        log_slopes = np.empty(n)
        slope_vars = np.empty(n)

        for t in range(n):
            x_pred = F @ x
            P_pred = F @ P @ F.T + Q

            z = log_prices[t]
            y = z - (H @ x_pred)[0]
            S = (H @ P_pred @ H.T)[0, 0] + R
            K = (P_pred @ H.T).flatten() / S

            x = x_pred + K * y
            P = (np.eye(2) - np.outer(K, H)) @ P_pred

            log_levels[t], log_slopes[t] = x
            slope_vars[t] = P[1, 1]

        return pd.DataFrame(
            {
                "log_level": log_levels,
                "log_slope": log_slopes,
                "slope_var": slope_vars,
            }
        )


# --------------------------------------------------------------------------- #
# 4. REGIME CLASSIFICATION - adaptive percentile-rank thresholding
# --------------------------------------------------------------------------- #
def classify_regime(
    df: pd.DataFrame,
    rank_window: int = 52,
    bullish_pct: float = 0.70,
    bearish_pct: float = 0.30,
    smoothing_bars: int = 3,
) -> pd.DataFrame:
    """
    SNR_t = log_slope_t / log_ATR_t
          (fractional growth rate, scaled by the current noise floor)

    Instead of comparing SNR to a fixed constant, we compute its trailing
    percentile RANK over `rank_window` bars: "is today's SNR higher than
    X% of the last N bars' SNR?" This makes the Bullish/Bearish/Sideways
    cutoffs self-calibrating per ticker, per timeframe, and per volatility
    regime - it can never structurally fail to reach one side, because it
    is defined relative to the instrument's own recent behavior rather than
    an arbitrary absolute number.

    A short (default 3-bar) MEDIAN filter is applied to the rank series
    before thresholding. A median filter rejects single-bar noise spikes
    without averaging in old information the way a moving average would -
    it does not reintroduce the phase lag this whole approach exists to
    avoid.
    """
    snr = df["log_slope"] / df["log_atr"]
    df["SNR"] = snr

    def _rank_of_last(x: pd.Series) -> float:
        return (x.iloc[-1] > x).mean()

    rank = snr.rolling(rank_window, min_periods=max(20, rank_window // 3)).apply(
        _rank_of_last, raw=False
    )
    if smoothing_bars > 1:
        rank = rank.rolling(smoothing_bars, min_periods=1).median()
    df["rank"] = rank

    # Estimation certainty from the filter's own posterior slope variance -
    # tighter posterior (lower variance) => higher confidence in the reading.
    slope_std = np.sqrt(df["slope_var"])
    certainty = 1.0 / (1.0 + (slope_std / slope_std.median()))

    regimes, confidences = [], []
    for r, c in zip(rank, certainty):
        if pd.isna(r):
            # regimes.append("Insufficient Data")
            regimes.append(0)
            confidences.append(0.0)
            continue

        if r >= bullish_pct:
            # regime = "Bullish Trend"
            regime = 1
            strength = (r - bullish_pct) / (1.0 - bullish_pct)
        elif r <= bearish_pct:
            # regime = "Bearish Trend"
            regime = -1
            strength = (bearish_pct - r) / bearish_pct
        else:
            # regime = "Sideways / Mean-Reverting"
            regime = 0
            # strength here = how close to the CENTER of the neutral band (0.5)
            strength = 1.0 - abs(r - 0.5) / (bullish_pct - 0.5)

        confidence = 100.0 * float(np.clip(0.6 * strength + 0.4 * c, 0.0, 1.0))
        regimes.append(regime)
        confidences.append(round(confidence, 1))

    # df["regime"] = regimes
    df["Trend"] = regimes
    df["confidence_pct"] = confidences
    return df


# --------------------------------------------------------------------------- #
# 5. OPTIONAL: GAUSSIAN HMM CROSS-CHECK
# --------------------------------------------------------------------------- #
def hmm_cross_check(returns: pd.Series, n_states: int = 3) -> str | None:
    """Independent second opinion: 3-state Gaussian HMM on log returns,
    states relabeled by fitted mean return (low->Bearish, mid->Sideways,
    high->Bullish). Returns None if hmmlearn isn't installed or fit fails."""
    if not _HMM_AVAILABLE:
        return None
    try:
        X = returns.dropna().values.reshape(-1, 1)
        if len(X) < 60:
            return None
        model = GaussianHMM(n_components=n_states, covariance_type="diag",
                             n_iter=200, random_state=42)
        model.fit(X)
        hidden_states = model.predict(X)
        order = np.argsort(model.means_.flatten())
        label_map = {order[0]: "Bearish", order[1]: "Sideways", order[2]: "Bullish"}
        return label_map[hidden_states[-1]]
    except Exception:
        return None

def determine_market_trend(df,window=52):
    ''' Window : small -> reactive to recent change
        Large makes it more conservative
        Eg, 26,52,104 '''

    freq = infer_bar_frequency(df.index)

    df["log_atr"] = compute_log_atr(df, window=14)

    kf = KalmanTrendFilter()
    kf_out = kf.run(np.log(df["Close"].values))
    kf_out.index = df.index
    df = pd.concat([df, kf_out], axis=1)

    # Rank window should not dwarf the dataset - shrink gracefully for short series.
    effective_window = min(window, max(20, len(df) // 3))
    df = classify_regime(df, rank_window=effective_window)
    # df = df.dropna(subset=["log_level", "log_atr"])
    df = df.drop(columns = ['log_atr','log_level', 'log_slope', 'slope_var', 'SNR', 'rank','confidence_pct'])

    return df

def calculate_true_range(df):
  """Calculates the True Range (TR) for a given DataFrame."""
  high_series = df['High']
  low_series = df['Low']
  close_series = df['Close']
  prev_close = close_series.shift(1)

  range1 = high_series - low_series
  range2 = abs(high_series - prev_close)
  range3 = abs(low_series - prev_close)

  df['TR'] = pd.DataFrame({'range1': range1, 'range2': range2, 'range3': range3}).max(axis=1)
  return df

def calculate_atr(df, period=14):
    """Calculates the Average True Range (ATR) using EMA of TR."""
    df['ATR'] = df['TR'].ewm(span=period, adjust=False).mean()
    return df

def classify_candles(df,ratio):
    tr = df['TR']
    atr = df['ATR']
    body_size = df['Close'] - df['Open']

    # Identify candle types
    df['Is_Exciting'] = (tr / atr > ratio['Exciting']['TR_ATR']) & ((body_size.abs() / tr) > ratio['Exciting']['BS_TR'])
    df['Is_Base'] = (tr / atr < ratio['Base']['TR_ATR']) & ((body_size.abs() / tr) < ratio['Base']['BS_TR'])
    df['Is_Explosive'] = (tr / atr > ratio['Explosive']['TR_ATR']) & ((body_size.abs() / tr) > ratio['Explosive']['BS_TR'])

    # df['Is_Exciting'] = df['Is_Exciting'] & ~df['Is_Explosive']


    return df

def compute_gap_flags(df: pd.DataFrame,gap_threshold=1.0) -> pd.Series:
    """Flags candles whose opening gap vs prior close exceeds a multiple of ATR."""
    prev_close = df['Close'].shift(1)
    gap = (df['Open'] - prev_close).abs()
    gap_atr_multiple = gap / df['ATR'].replace(0, np.nan)
    df['Gapped'] = gap_atr_multiple > gap_threshold
    return df

def compute_volume_zscore(df: pd.DataFrame, lookback: int) -> pd.Series:
    """Rolling z-score of volume -- flags abnormally thin/illiquid trading."""
    if 'Volume' not in df.columns:
        return pd.Series(np.nan, index=df.index)
    roll_mean = df['Volume'].rolling(lookback).mean()
    roll_std = df['Volume'].rolling(lookback).std().replace(0, np.nan)
    Volume_Zscore = (df['Volume'] - roll_mean) / roll_std
    df['High_Volume'] = Volume_Zscore > 1.5

    return df

def compute_choppiness_index(df: pd.DataFrame, period: int,chop_indx: float) -> pd.Series:
    """Choppiness Index (0-100). High = sideways/choppy, Low = trending."""
    high_max = df['High'].rolling(period).max()
    low_min = df['Low'].rolling(period).min()
    tr_sum = df['TR'].rolling(period).sum()
    span = (high_max - low_min).replace(0, np.nan)
    choppiness = 100 * np.log10(tr_sum / span) / np.log10(period)
    # df['Choppiness'] = choppiness > chop_indx
    df['Trending'] = choppiness < chop_indx
    return df

def detect_swing_points(df: pd.DataFrame, lookback: int) -> pd.DataFrame:
    """
    Fractal-style swing high/low detection used by BOS / OB / Sweep logic.

    NOTE ON CAUSALITY: a fractal swing at bar i is only *confirmed* once we've
    seen `lookback` bars after it (the centered window needs the right-hand
    side to know bar i was a local extreme). `Swing_High`/`Swing_Low` below
    are therefore NOT safe to use directly at their own index -- use
    `get_confirmed_swing_levels()` for any decision made "as of" bar i, which
    correctly delays the signal until it would actually have been known.
    """
    df['Swing_High'] = df['High'] == df['High'].rolling(2 * lookback + 1, center=True).max()
    df['Swing_Low'] = df['Low'] == df['Low'].rolling(2 * lookback + 1, center=True).min()
    return df

def get_confirmed_swing_levels(df: pd.DataFrame, lookback: int):
    """
    Returns (last_swing_high, last_swing_low) as they would have been *knowable*
    at each bar -- i.e. with the `lookback` bars of look-ahead baked into
    `detect_swing_points`'s centered window removed.

    Bug fixed: the previous version shifted the raw (centered, non-causal)
    Swing_High/Swing_Low flags by only 1 bar before use in BOS/OB/Sweep
    detection. Since confirming a swing at bar i requires seeing bars up to
    i + lookback, a shift of 1 leaked up to (lookback - 1) bars of future
    information into every downstream signal -- a classic repainting bug that
    silently inflates backtest performance. Shifting by (lookback + 1) instead
    ensures the swing level used at bar i was fully confirmed by bar i - 1.
    """
    confirm_shift = lookback + 1
    last_swing_high = df['High'].where(df['Swing_High']).ffill().shift(confirm_shift)
    last_swing_low = df['Low'].where(df['Swing_Low']).ffill().shift(confirm_shift)
    return last_swing_high, last_swing_low


def compute_bos_flags_n_liquidity_sweep(df: pd.DataFrame, swing_lookback,sweep_wick_ratio) -> pd.DataFrame:
    """Break of Structure: close beyond the most recent *confirmed* swing high/low."""
    last_swing_high, last_swing_low = get_confirmed_swing_levels(df, swing_lookback)
    df['BOS_Bull'] = df['Close'] > last_swing_high
    df['BOS_Bear'] = df['Close'] < last_swing_low

    """Liquidity Sweep / stop-hunt: wick beyond a swing high/low, closes back inside."""
    candle_range = (df['High'] - df['Low']).replace(0, np.nan)
    upper_wick = df['High'] - df[['Open', 'Close']].max(axis=1)
    lower_wick = df[['Open', 'Close']].min(axis=1) - df['Low']

    df['Sweep_High'] = (df['High'] > last_swing_high) & \
                        (df['Close'] < last_swing_high) & \
                        ((upper_wick / candle_range) > sweep_wick_ratio)

    df['Sweep_Low'] = (df['Low'] < last_swing_low) & \
                       (df['Close'] > last_swing_low) & \
                       ((lower_wick / candle_range) > sweep_wick_ratio)

    return df


def detect_order_blocks(df: pd.DataFrame, require_bos_for_order_block=0) -> pd.DataFrame:
    """
    Order Block (SMC): last opposite-colored candle immediately before an
    impulsive move that produces a Break of Structure.
    """
    is_down = df['Close'] < df['Open']
    is_up = df['Close'] > df['Open']

    bull_ob = is_down.shift(1) & df['BOS_Bull']
    bear_ob = is_up.shift(1) & df['BOS_Bear']

    if require_bos_for_order_block:
        df['Bullish_OB'] = bull_ob
        df['Bearish_OB'] = bear_ob
    else:
        df['Bullish_OB'] = is_down.shift(1) & df['Is_Explosive'] & (df['Close'] > df['Open'])
        df['Bearish_OB'] = is_up.shift(1) & df['Is_Explosive'] & (df['Close'] < df['Open'])

    return df

def identify_zones(df, ratio):
    """Calculates indicators and identifies potential DZone/SZone locations, including continuous zones."""
    df = calculate_true_range(df.copy()) # Adding TR
    df = calculate_atr(df)               # Adding ATR
    df = classify_candles(df,ratio)      # Adding Is_base, Is_Exciting, Is_Explosive to the Df
    df = compute_gap_flags(df,gap_threshold=0.5)           # Adding Gap to the Df
    df = compute_volume_zscore(df, lookback=22) # 1 month  # Adding High_Volume
    df = compute_choppiness_index(df,period=22,chop_indx=38.2)  # Chopiness , Trending < 38.2 < AmbiguousTransitioning < 61.8 < ChopplySideways
    df = detect_swing_points(df, lookback=5) # Adding Swing_High , Swing_Low
    df = compute_bos_flags_n_liquidity_sweep(df, swing_lookback = 22,
                                             sweep_wick_ratio= 3) # Adding BOS_Bull , BOS_Bear, Sweep_High, Sweep_Low # Unclear how BOS will work in Contnuous zones
    df = detect_order_blocks(df,require_bos_for_order_block=0) # Adding Bullish_OB, Bearish_OB


    df['date'] = df.index.strftime('%Y-%m-%d')

    # Basic Pattern: Candle[idx-2] (Exciting) -> Candle[idx-1] (Base) -> Candle[idx] (Explosive)
    df['Zone_Created'] = df['Is_Exciting'].shift(2) & df['Is_Base'].shift(1) & df['Is_Explosive']

    df['Is Continuous'] = False
    df['Is Demand'] = False

    df['Proximal'] = np.nan
    df['Distal'] = np.nan
    df['Target'] = np.nan

    # Demand Zones (Reversal: Drop-Base-Rally | Continuous: Rally-Base-Rally)
    cond_rev_d  = (df['Close'].shift(2) < df['Open'].shift(2)) & (df['Close'] > df['Open'])
    cond_cont_d = (df['Close'].shift(2) > df['Open'].shift(2)) & (df['Close'] > df['Open'])

    # Supply Zones (Reversal: Rally-Base-Drop | Continuous: Drop-Base-Drop)
    cond_rev_s  = (df['Close'].shift(2) > df['Open'].shift(2)) & (df['Close'] < df['Open'])
    cond_cont_s = (df['Close'].shift(2) < df['Open'].shift(2)) & (df['Close'] < df['Open'])

    d_mask = df['Zone_Created'] & (cond_cont_d | cond_rev_d)
    s_mask = df['Zone_Created'] & (cond_rev_s | cond_cont_s)

    df.loc[d_mask,'Is Demand'] = True
    df.loc[df['Zone_Created'] & (cond_cont_d | cond_cont_s),'Is Continuous'] = True

    # Calculate level series for entire DF first to avoid index mismatch
    d_prox_series = df[['Open','Close']].shift(1).max(axis=1)
    d_dist_base = df['Low'].shift(1)
    d_dist_rev = df['Low'].rolling(window=3, min_periods=1).min()

    s_prox_series = df[['Open','Close']].shift(1).min(axis=1)
    s_dist_base = df['High'].shift(1)
    s_dist_rev = df['High'].rolling(window=3, min_periods=1).max()

    # Apply Demand calculations
    if d_mask.any():
        df.loc[d_mask, 'Proximal'] = d_prox_series[d_mask]
        df.loc[d_mask, 'Distal'] = np.where(df.loc[d_mask, 'Is_Continuous'], d_dist_base[d_mask], d_dist_rev[d_mask])

    # Apply Supply calculations
    if s_mask.any():
        df.loc[s_mask, 'Proximal'] = s_prox_series[s_mask]
        # Access values from series using the mask to ensure alignment
        df.loc[s_mask, 'Distal'] = np.where(df.loc[s_mask, 'Is_Continuous'], s_dist_base[s_mask], s_dist_rev[s_mask])

    # Target calculation
    df['Target'] = df['Proximal'] + 2 * (df['Proximal'] - df['Distal'])

    return df

def identity_zones_with_multibase(df,ratio,max_base_candles=10):

  """Calculates indicators and identifies potential DZone/SZone locations, including continuous zones."""
  df = calculate_true_range(df.copy()) # Adding TR
  df = calculate_atr(df)               # Adding ATR
  df = classify_candles(df,ratio)      # Adding Is_base, Is_Exciting, Is_Explosive to the Df
  df = compute_gap_flags(df,gap_threshold=0.5)           # Adding Gap to the Df
  df = compute_volume_zscore(df, lookback=22) # 1 month  # Adding High_Volume
  df = compute_choppiness_index(df,period=22,chop_indx=38.2)  # Chopiness , Trending < 38.2 < AmbiguousTransitioning < 61.8 < ChopplySideways
  df = detect_swing_points(df, lookback=5) # Adding Swing_High , Swing_Low
  df = compute_bos_flags_n_liquidity_sweep(df, swing_lookback = 22,
                                            sweep_wick_ratio= 3) # Adding BOS_Bull , BOS_Bear, Sweep_High, Sweep_Low # Unclear how BOS will work in Contnuous zones
  df = detect_order_blocks(df,require_bos_for_order_block=0) # Adding Bullish_OB, Bearish_OB

  n                         = len(df)
  is_exc,is_base,is_exp     = df['Is_Exciting'],df['Is_Base'],df['Is_Explosive']
  opens,closes              = df['Open'].values,df['Close'].values
  highs,lows                = df['High'].values,df['Low'].values

  zone_created              = np.zeros(n,dtype=bool)
  base_len                  = np.zeros(n,dtype=int)
  leg_in_idx                = np.full(n,-1,dtype=int)
  base_start_idx            = np.full(n,-1,dtype=int)
  base_end_idx              = np.full(n,-1,dtype=int)

  for i in range(2,n):
    if not is_exp.iloc[i]:
      continue

    j,cnt = i-1,0
    while j>=0 and is_base.iloc[j] and cnt<max_base_candles:
      cnt += 1
      j -= 1

    if cnt>=1 and j>=0 and is_exc.iloc[j]:
      zone_created[i] = True
      base_len[i] = cnt
      leg_in_idx[i] = j
      base_start_idx[i] = j+1
      base_end_idx[i] = i-1

  # df['date']            = df.index.strftime('%Y-%m-%d')
  df['Zone_Created']    = zone_created
  df['Base Count']     = base_len
  df['Leg_In_Idx']      = leg_in_idx
  df['Base_Start_Idx']  = base_start_idx
  df['Base_End_Idx']    = base_end_idx
  df['Is Continuous']   = False
  df['Is Demand']       = False
  df['Proximal']        = np.nan
  df['Distal']          = np.nan

  zone_indices = np.where(zone_created)[0]
  for i in zone_indices:
    li,bs,be = leg_in_idx[i],base_start_idx[i],base_end_idx[i]
    leg_in_bull  = closes[li]  > opens[li]
    leg_out_bull = closes[i]  > opens[i]

    is_demand = leg_out_bull
    is_continuous = (leg_in_bull == leg_out_bull)

    base_top = np.maximum(opens[bs:be+1],closes[bs:be+1])
    base_bot = np.minimum(opens[bs:be+1],closes[bs:be+1])
    prox,dist = base_top.max(),base_bot.min()

    if is_demand:
      proximal = base_top.max()
      distal = lows[bs:be+2].min()
      # distal = lows[bs:be+1].min() if is_continuous else lows[bs:be + 2].min()
    else:
      proximal = base_bot.min()
      distal = highs[bs:be+2].max()
      # distal = highs[bs:be+1].max() if is_continuous else highs[bs:be + 2].max()

    df.at[df.index[i], 'Is Demand'] = is_demand
    df.at[df.index[i], 'Is Continuous'] = is_continuous
    df.at[df.index[i], 'Proximal'] = proximal
    df.at[df.index[i], 'Distal'] = distal

  risk = df['Proximal'] - df['Distal']
  df['Target'] = df['Proximal'] + 2 * risk

  return df

def check_refined_htf_support(daily_row, htf_df, creation_date):
    """
    Checks for HTF support with two conditions:
    1. HTF Proximal is within 10% of Daily Distal.
    2. HTF zone has not been breached (price < distal for demand) before daily creation.
    """
    is_demand = daily_row['Is Demand']
    daily_dist = daily_row['Distal']

    # Filter HTF zones of same type created before or on the daily creation date
    valid_htf_zones = htf_df[(htf_df.index <= creation_date) &
                             (htf_df['Zone_Created'] == True) &
                             (htf_df['Is Demand'] == is_demand)]

    if valid_htf_zones.empty:
        return False

    for h_idx, h_row in valid_htf_zones[::-1].iterrows():
        h_prox = h_row['Proximal']
        h_dist = h_row['Distal']

        # 1. Proximity Check: HTF Proximal within 10% of Daily Distal
        proximity_diff = abs(daily_dist - h_prox) / h_prox
        flg1 = proximity_diff <= 0.10
        flg2 = (is_demand and h_dist <= daily_dist) or (not is_demand and h_dist >= daily_dist)

        if flg1 and flg2:
            # 2. Breach Check: Has price breached HTF Distal since HTF creation until Daily creation?
            # For Demand: Breach if Low < HTF Distal. For Supply: Breach if High > HTF Distal.
            period_data = htf_df.loc[h_idx : creation_date]

            if is_demand:
                breached = (period_data['Low'] < h_dist).any()
            else:
                breached = (period_data['High'] > h_dist).any()

            if not breached:
                htf_df.loc[h_idx,'Support'] = True
                return True # Found at least one valid supporting HTF zone

    return False

def calculate_trade_score(ticker,df, weekly_df=None, monthly_df=None, nifty_1d_df=None, nifty_1wk_df=None, nifty_1mo_df=None):
    """Calculates a score for each zone based on Freshness, Strength, Base Count, Weekly Trend, and HTF Support."""
    # Initialize columns
    df_ts = df[df['Zone_Created'] == True].copy()

    df_ts['Freshness'] = False
    df_ts['Strength'] = 0
    df_ts['Gapped'] = False
    df_ts['High Volume'] = False
    df_ts['Trending'] = False
    df_ts['Swing Point'] = False
    df_ts['BOS'] = False
    df_ts['OB'] = False
    df_ts['Sweep'] = False
    df_ts['Trend Support'] = False
    df_ts['ITF Support'] = False
    df_ts['HTF Support'] = False
    df_ts['N_LTF Support'] = False
    df_ts['N_ITF Support'] = False
    df_ts['N_HTF Support'] = False
    # df_ts['HTF_Support_w'] = False
    # df_ts['Nifty_1d_Support'] = False # New column for Nifty 50 daily support
    # df_ts['Nifty_1wk_Support'] = False # New column for Nifty 50 weekly support
    # df_ts['Nifty_1mo_Support'] = False # New column for Nifty 50 monthly support

    df_ts = df_ts.drop(columns=['Close', 'High', 'Low', 'Open', 'Volume', 'TR', 'ATR', 'Is_Exciting',
                                'Is_Base','Is_Explosive','Zone_Created','Proximal','Distal',
                                'Target','Swing_High','Swing_Low','BOS_Bull', 'BOS_Bear','High_Volume',
                                'Sweep_High', 'Sweep_Low', 'Bullish_OB', 'Bearish_OB',
                                'Leg_In_Idx', 'Base_Start_Idx', 'Base_End_Idx'])

    # Insert ticker as first column
    df_ts.insert(0, 'Ticker', ticker)

    if weekly_df is not None and not weekly_df.empty:
      # weekly_df = determine_market_trend(weekly_df, fast_period = 20, slow_period = 50)
      weekly_df = determine_market_trend(weekly_df, window=52)

    # Identify where zones were created (The Leg-out candle)
    zone_indices = np.where(df['Zone_Created'] == True)[0]

    for ind,idx in enumerate(zone_indices):
        if idx >= len(df):
            continue

        row = df.iloc[idx]
        prox, dist = row['Proximal'], row['Distal']
        if pd.isna(prox) or pd.isna(dist):
            continue

        is_demand = row['Is Demand']
        creation_date = df.index[idx]

        # --- 1. Freshness Logic ---
        future_data = df.iloc[idx+1:]
        if not future_data.empty:
            if is_demand:
                touched = (future_data['Low'] <= prox).any()
            else:
                touched = (future_data['High'] >= prox).any()
            df_ts.at[df.index[idx], 'Freshness'] = False if touched else True
        else:
            df_ts.at[df.index[idx], 'Freshness'] = True

        # --- 2. Strength ---
        strength_count = 0
        for i in range(idx, len(df)):
            if df.iloc[i]['Is_Exciting'] or df.iloc[i]['Is_Explosive']:
                strength_count += 1
            else:
                break
        df_ts.at[df.index[idx], 'Strength'] = strength_count

        # --- 3. Number of Base Candles ---
        base_count = 0
        for i in range(idx-1, -1, -1):
            if df.iloc[i]['Is_Base']:
                base_count += 1
            else:
                break
        df_ts.at[df.index[idx], 'Base Count'] = base_count

        # --- 3a. Gap Logic ---
        # flg = df.iloc[idx-2:idx+1]['Gapped'].any()
        flg = df.iloc[idx-2:idx+strength_count]['Gapped'].any()
        df_ts.at[df.index[idx], 'Gapped'] = flg

        # --- 3b. Volume Z Score ---
        # flg = df.iloc[idx-2:idx+1]['High_Volume'].any()
        flg = df.iloc[idx-2:idx+strength_count]['High_Volume'].any()
        df_ts.at[df.index[idx], 'High Volume'] = flg

        # --- 3c. Choppiness Index ---
        # flg = df.iloc[idx-2:idx+1]['Trending'].any()
        flg = df.iloc[idx-2:idx+strength_count]['Trending'].any()
        df_ts.at[df.index[idx], 'Trending'] = flg

        # --- 3d. Swing High/Low ---
        flg1 = df.iloc[idx-2:idx+strength_count]['Swing_High'].any()
        flg2 = df.iloc[idx-2:idx+strength_count]['Swing_Low'].any()
        flg = flg1 or flg2
        df_ts.at[df.index[idx], 'Swing Point'] = flg

        # --- 3d. BOS_Bull / BOS_Bear ---
        if is_demand:
          flg = df.iloc[idx-2:idx+strength_count]['BOS_Bull'].any()
        else:
          flg = df.iloc[idx-2:idx+strength_count]['BOS_Bear'].any()
        df_ts.at[df.index[idx], 'BOS'] = flg

        # --- 3e. Sweep High / Sweeep Low ---
        if is_demand:
          flg = df.iloc[idx-2:idx+strength_count]['Sweep_High'].any()
        else:
          flg = df.iloc[idx-2:idx+strength_count]['Sweep_Low'].any()
        df_ts.at[df.index[idx], 'Sweep'] = flg

        # --- 3f. Bullish_OB / Bearish_OB ---
        flg = df.iloc[idx]['Bullish_OB'] if is_demand else df.iloc[idx]['Bearish_OB']
        df_ts.at[df.index[idx], 'OB'] = flg

        # --- 4a. Weekly Timeframe Intermediate TF Support and Trend Favour ---
        if weekly_df is not None and not weekly_df.empty:
          df_ts.at[df.index[idx], 'ITF Support'] = check_refined_htf_support(row, weekly_df, creation_date)

          available_weekly_dates = weekly_df.index[weekly_df.index <= creation_date]
          if not available_weekly_dates.empty:
            last_weekly_date = available_weekly_dates[-1]
            w_trend = weekly_df.at[last_weekly_date, 'Trend']
            if (is_demand and (w_trend==1)) or (not is_demand and (w_trend==-1)):
              df.at[df.index[idx], 'Trend Support'] = True


        # --- 4b. Monthly Timeframe Higher TF Support ---
        if monthly_df is not None and not monthly_df.empty:
          df_ts.at[df.index[idx], 'HTF Support'] = check_refined_htf_support(row, monthly_df, creation_date)

        # --- 4c. Nifty 50 Support (Daily Overlap) ---
        if nifty_1d_df is not None and not nifty_1d_df.empty:
          df_ts.at[df.index[idx], 'N_LTF Support'] = check_refined_htf_support(row, nifty_1d_df, creation_date)

        # --- 4d. Nifty 50 Support (Weekly Overlap) ---
        if nifty_1wk_df is not None and not nifty_1wk_df.empty:
          df_ts.at[df.index[idx], 'N_ITF Support'] = check_refined_htf_support(row, nifty_1wk_df, creation_date)

        # --- 4e. Nifty 50 Support (Monthly Overlap) ---
        if nifty_1mo_df is not None and not nifty_1mo_df.empty:
          df_ts.at[df.index[idx], 'N_HTF Support'] = check_refined_htf_support(row, nifty_1mo_df, creation_date)
    return df_ts,weekly_df

def backtest_zones(ticker, df,realistic_fills=True):
    """Simulates trades for the identified valid zones."""
    zone_created  = df['Zone_Created'] == True
    df_bt         = pd.DataFrame(index=df[zone_created].index)
    df_bt         = df_bt.rename({'date':'Date Created'})

    df_bt['Ticker'] = ticker
    df_bt['Entry Date'] = pd.NaT
    df_bt['Exit Date'] = pd.NaT
    df_bt['Entry Price'] = np.nan
    df_bt['Exit Price'] = np.nan
    df_bt['Outcome'] = ''
    df_bt['P/L'] = np.nan
    df_bt['R-Multiple'] = np.nan
    df_bt['Proximal'] = np.nan
    df_bt['Distal'] = np.nan
    df_bt['Target'] = np.nan
    df_bt['Piercing_Depth'] = np.nan

    zone_indices  = np.where(zone_created)[0]
    for i,ind in enumerate(zone_indices):
        zone = df.iloc[ind]

        df_test = df.iloc[ind+1:]
        if df_test.empty:
            df_bt.at[df.index[ind], 'Outcome'] = 'No Entry'
            continue

        is_demand           = zone['Is Demand']
        prox, dist, tar     = zone['Proximal'], zone['Distal'], zone['Target']
        risk                = abs(prox - dist)
        if risk == 0:
          df_bt.at[df.index[ind], 'Outcome'] = 'Proximal == Distal'
          continue

        entry_cond = (df_test['Open'] <= prox) | (df_test['Low'] <= prox) if is_demand else (df_test['Open'] >= prox) | (df_test['High'] >= prox)

        entry_idx_rel = np.where(entry_cond)[0]
        if entry_idx_rel.size == 0:
          df_bt.at[df.index[ind], 'Outcome'] = 'No Entry'
          continue

        entry_idx = ind + 1 + entry_idx_rel[0]
        entry_candle = df.iloc[entry_idx]
        open_px = entry_candle['Open']
        close_px = entry_candle['Close']

        if realistic_fills:
          entry_price = min(open_px,prox) if is_demand else max(close_px,prox)
        else:
          entry_price = prox

        df_after              = df.iloc[entry_idx:]
        tar_c                 = (df_after['High'] >= tar) if is_demand else (df_after['Low'] <= tar)
        sl_c                  = (df_after['Low'] <= dist) if is_demand else (df_after['High'] >= dist)
        itar, isl             = np.where(tar_c)[0], np.where(sl_c)[0]
        itar_idx              = entry_idx + itar[0] if itar.size > 0 else np.inf
        isl_idx               = entry_idx + isl[0] if isl.size > 0 else np.inf

        if np.isinf(itar_idx) and np.isinf(isl_idx):
            exit_idx, exit_price, outcome = len(df)-1, df['Close'].iloc[-1], "No Exit (Open)"
        elif isl_idx <= itar_idx:
            exit_idx, exit_price, outcome = isl_idx, dist, "Stop Loss"

            exit_candle_open = df.iloc[exit_idx]['Open']
            if is_demand & (exit_candle_open < exit_price): # To handle gapped entry/ gapped exit
                exit_price = exit_candle_open
            if (not is_demand) & (exit_candle_open > exit_price): # To handle gapped entry/ gapped exit
                exit_price = exit_candle_open
        else:
            exit_idx, exit_price, outcome = itar_idx, tar, "Profit"

        pnl = (exit_price - entry_price) if is_demand else (entry_price - exit_price)
        if pnl == 0.0:
          outcome = 'Invalidated (Gap Through Zone)'

        if outcome == "Stop Loss":
          pnl = -abs(pnl)

        if outcome == "Profit":
          #print(ind,entry_idx,exit_idx,df.shape)
          trade_data = df.iloc[entry_idx:exit_idx+1]
          if is_demand:
              worst_price = trade_data['Low'].min()
              pierce = (prox - worst_price) / risk
          else:
              worst_price = trade_data['High'].max()
              pierce = (worst_price - prox) / risk
          piercing_depth = max(0, min(1, pierce))
          df_bt.at[df.index[ind], 'Piercing_Depth'] = round(piercing_depth, 2)

        df_bt.at[df.index[ind], 'Entry Date']   = df.index[entry_idx]
        df_bt.at[df.index[ind], 'Exit Date']    = df.index[exit_idx]
        df_bt.at[df.index[ind], 'Entry Price']  = round(entry_price, 2)
        df_bt.at[df.index[ind], 'Exit Price']   = round(exit_price, 2)
        df_bt.at[df.index[ind], 'Outcome']      = outcome
        df_bt.at[df.index[ind], 'P/L']          = round(pnl, 2)
        df_bt.at[df.index[ind], 'R-Multiple']   = round(pnl/risk, 2)
        df_bt.at[df.index[ind], 'Proximal']     = round(prox, 2)
        df_bt.at[df.index[ind], 'Distal']       = round(dist, 2)
        df_bt.at[df.index[ind], 'Target']       = round(tar, 2)
    return df_bt

def run_risk_management_simulation(df_bt, initial_capital, risk_percentage_per_trade):
    """
    Applies risk management rules to a summary DataFrame of trades, accounting for sequential trades.

    Args:
        summary_df (pd.DataFrame): DataFrame containing trade summaries with 'Entry Date', 'Exit Date', 'Proximal', 'Distal', 'R-Multiple' columns.
        initial_capital (float): The starting capital for the simulation.
        risk_percentage_per_trade (float): The percentage of capital risked per trade (e.g., 0.01 for 1%).

    Returns:
        pd.DataFrame: The summary_df with added risk management columns.
    """
    valid_outcome = (df_bt['Outcome'] == 'Profit') | (df_bt['Outcome'] == 'Stop Loss')
    df_rm         = df_bt[valid_outcome].copy()

    # Initialize Capital and other columns with float dtype
    df_rm['Capital_At_Entry'] = np.float64(initial_capital)
    df_rm['Risk_Amount_Per_Trade'] = np.float64(0.0)
    df_rm['Quantity'] = np.float64(0.0) # Quantity can be float before casting to int
    df_rm['Trade_PnL'] = np.float64(0.0) # To store the actual profit/loss for the trade based on quantity
    df_rm['Active_Trade'] = False # New column to track if a trade was taken
    df_rm['Capital_After_Trade'] = np.float64(initial_capital) # New column for capital after each trade

    # Ensure relevant date columns are datetime objects
    df_rm['Entry Date'] = pd.to_datetime(df_rm['Entry Date'])
    df_rm['Exit Date'] = pd.to_datetime(df_rm['Exit Date'])

    current_capital = initial_capital
    active_trade_exit_date = None # Tracks the exit date of an active trade

    for index, row in df_rm.iterrows():
        trade_entry_date = row['Entry Date']
        trade_exit_date = row['Exit Date']

        # Check if a trade is currently active and if the current trade's entry date is before or on the active trade's exit date
        if 1:
          if active_trade_exit_date is not None and trade_entry_date <= active_trade_exit_date:
              # Skip this trade as another is active or just exited on the same day
              df_rm.loc[index, 'Capital_At_Entry'] = current_capital
              df_rm.loc[index, 'Active_Trade'] = False
              df_rm.loc[index, 'Capital_After_Trade'] = current_capital
              continue

        # If no trade is active or active_trade_exit_date has passed
        df_rm.loc[index, 'Capital_At_Entry'] = current_capital
        df_rm.loc[index, 'Active_Trade'] = True

        # Calculate Risk Amount per Trade
        risk_amount_per_trade = current_capital * risk_percentage_per_trade
        df_rm.loc[index, 'Risk_Amount_Per_Trade'] = risk_amount_per_trade

        # Calculate Quantity
        price_difference = abs(row['Proximal'] - row['Distal'])
        if price_difference == 0:
            quantity = 0
        else:
            quantity = risk_amount_per_trade / price_difference
        df_rm.loc[index, 'Quantity'] = int(quantity) # Assuming whole units for simplicity

        # Calculate actual PnL for the trade
        #trade_pnl = row['R-Multiple'] * risk_amount_per_trade
        trade_pnl = row['P/L'] * int(quantity)
        df_rm.loc[index, 'Trade_PnL'] = trade_pnl

        # Update current capital after this trade
        current_capital += trade_pnl
        df_rm.loc[index, 'Capital_After_Trade'] = current_capital

        df_rm.loc[index, 'Zone_Type'] = 'Demand' if row['Target'] > row['Proximal'] else 'Supply'

        # Set the exit date for the newly active trade
        active_trade_exit_date = trade_exit_date
    df_rm = df_rm.drop(columns=['Entry Price','Exit Price','Outcome','P/L','R-Multiple','Proximal','Distal','Target'])

    return df_rm

def run_strategy_for_ticker(ticker, data, ratio,
                            nifty_1d_df=None,nifty_1wk_df=None,nifty_1mo_df=None,C=100000,risk=0.01):
    """Modular orchestrator for the backtest strategy."""
    #print(f"Processing: {ticker}")
    # df_with_zone = identify_zones(data[ticker]['1d'], ratio['GEN.NS']['1d'])
    out = {'anal':{'ts':None,'bt':None,'rm':None},
            'zones':{'1d':None,'1wk':None,'1mo':None}}

    df_with_zones_1d = identity_zones_with_multibase(data[ticker]['1d'], ratio['GEN.NS']['1d'])
    df_with_zones_1wk = identity_zones_with_multibase(data[ticker]['1wk'], ratio['GEN.NS']['1wk'])
    df_with_zones_1mo = identity_zones_with_multibase(data[ticker]['1mo'], ratio['GEN.NS']['1mo'])

    if df_with_zones_1d.empty:
      print(f'No Zones found for {ticker}')
      return out
    out['zones'] = {'1d':df_with_zones_1d,'1wk':df_with_zones_1wk,'1mo':df_with_zones_1mo}

    df_ts,df_with_zones_1wk = calculate_trade_score(ticker,
                                                    df_with_zones_1d, df_with_zones_1wk, df_with_zones_1mo,
                                                    nifty_1d_df, nifty_1wk_df, nifty_1mo_df)
    out['anal']['ts'] = df_ts

    df_bt = backtest_zones(ticker, df_with_zones_1d)
    if df_bt.empty:
      print(f'No Trades found for {ticker}')
      return out
    out['anal']['bt'] = df_bt

    # summary_df = calculate_single_ts(df_with_zones_1d)
    # #metrics = calculate_performance(ticker, summary_df)

    df_rm = run_risk_management_simulation(df_bt,C, risk)
    out['anal']['rm'] = df_rm

    return out

def calculate_single_ts(df):
    # Create a copy to prevent SettingWithCopyWarning
    df = df.copy()

    # ----------------------------------------------------
    # CRITICAL FILTER: FRESHNESS
    # Tested zones are disqualified (Score = 0)
    # ----------------------------------------------------
    # Assumes 'Freshness' is True for fresh zones, False for tested
    # fresh_mask = df["Freshness"] == True
    fresh_mask = np.ones(len(df), dtype=bool)

    # ----------------------------------------------------
    # PILLAR 1: ZONE STRUCTURE & QUALITY (Max 3 Points)
    # ----------------------------------------------------

    # Strength mapping (Adjust strings to match your data exactly)
    strength_conditions = [
        df["Strength"].isin(["Strong", "High", 3]),
        df["Strength"].isin(["Medium", "Avg", 2]),
    ]
    strength_choices = [1.5, 0.75]
    p1_strength = np.select(strength_conditions, strength_choices, default=0.0)

    # Base Count mapping
    base_conditions = [df["Base Count"].between(1, 3), df["Base Count"].between(4, 5)]
    base_choices = [0.5, 0.25]
    p1_base = np.select(base_conditions, base_choices, default=0.0)

    # Is Continuous (Reversal DBD/RBR = 0.5, Continuous RBR/DBD = 0.0)
    p1_continuous = np.where(df["Is Continuous"] == False, 0.5, 0.0)

    # Opposite Candle before explosive candle, confirming order blocks
    p1_opp_candle = np.where(
        df["OB"] == True, 0.5, 0.0
    )

    pillar_1 = p1_strength + p1_base + p1_continuous + p1_opp_candle

    # ----------------------------------------------------
    # PILLAR 2: LIQUIDITY & MOMENTUM (Max 3 Points)
    # ----------------------------------------------------
    p2_bos = np.where(df["BOS"] == True, 1.0, 0.0)
    p2_sweep = np.where(df["Sweep"] == True, 0.5, 0.0)  # Handles your typo 'Sweep Pont'
    p2_volume = np.where(df["High Volume"] == True, 0.5, 0.0)
    p2_gapped = np.where(df["Gapped"] == True, 0.5, 0.0)
    p2_swing = np.where(df["Swing Point"] == True, 0.5, 0.0)

    pillar_2 = p2_bos + p2_sweep + p2_volume + p2_gapped + p2_swing

    # ----------------------------------------------------
    # PILLAR 3: HIGHER TIME FRAME LOCATION & TREND (Max 2 Points)
    # ----------------------------------------------------
    p3_trending = np.where(df["Trending"] == True, 0.5, 0.0)
    p3_support = np.where(df["Trend Support"] == True, 0.5, 0.0)
    p3_weekly = np.where(df["ITF Support"] == True, 0.5, 0.0)
    p3_monthly = np.where(df["HTF Support"] == True, 0.5, 0.0)

    pillar_3 = p3_trending + p3_support + p3_weekly + p3_monthly
    # Cap Pillar 3 at 2.0 max just in case
    pillar_3 = np.clip(pillar_3, 0.0, 2.0)

    # ----------------------------------------------------
    # PILLAR 4: INDEX CONFLUENCE (NIFTY 50) (Max 2 Points)
    # ----------------------------------------------------
    p4_nifty_daily = np.where(df["N_LTF Support"] == True, 0.5, 0.0)
    p4_nifty_weekly = np.where(df["N_ITF Support"] == True, 0.75, 0.0)
    p4_nifty_monthly = np.where(df["N_HTF Support"] == True, 0.75, 0.0
    )

    pillar_4 = p4_nifty_daily + p4_nifty_weekly + p4_nifty_monthly
    # Institutionally cap Nifty confluence weights to a maximum of 2.0 points
    pillar_4 = np.clip(pillar_4, 0.0, 2.0)

    # ----------------------------------------------------
    # AGGREGATION & BUCKETING
    # ----------------------------------------------------
    # Total Score calculation
    total_score = pillar_1 + pillar_2 + pillar_3 + pillar_4

    # Apply Freshness Filter (If not fresh, score is forced to 0.0)
    df["Trade Score"] = np.where(fresh_mask, total_score, 0.0)

    # Bucket trades into Actionable Execution Tiers
    tier_conditions = [
        df["Trade Score"] >= 8.5,
        df["Trade Score"].between(7.0, 8.49),
        (df["Trade Score"] < 7.0) & (df["Trade Score"] > 0),
    ]
    tier_choices = [
        "Tier A+ (Direct Limit Order)",
        "Tier B (Wait for 15m Confirmation)",
        "Tier C (Skip / Low Probability)",
    ]
    df["Execution Tier"] = np.select(
        tier_conditions, tier_choices, default="Disqualified (Tested Zone)"
    )
    df['p1'] = pillar_1
    df['p2'] = pillar_2
    df['p3'] = pillar_3
    df['p4'] = pillar_4

    return df

def plot_stock_zones(ticker, df,htf_df=None,show_swing=False,
                     only_supporting=False,show_trend=False,multibase=False):
    """Creates an interactive Plotly chart with identified zones."""
    fig = go.Figure()

    # 1. Candlestick Chart
    fig.add_trace(go.Candlestick(
        x=df.index,
        open=df['Open'],
        high=df['High'],
        low=df['Low'],
        close=df['Close'],
        name='Price'
    ))


    # 2. Add HTF Zones (Weekly/Monthly) if provided
    if htf_df is not None and not htf_df.empty:
        if only_supporting:
            htf_zone_indices = np.where(htf_df['Support'] == True)[0]
        else:
            htf_zone_indices = np.where(htf_df['Zone_Created'] == True)[0]

        for idx in htf_zone_indices:
            row = htf_df.iloc[idx]
            is_demand = row['Is Demand']
            # We align HTF zones to the daily index to prevent gaps
            x0 = row.name
            x1 = df.index[-1]

            if is_demand:
              # breach_ind = np.where(htf_df.iloc[idx+1:]['Low'] <= row['Distal'])[0]
              breach_ind = np.where(htf_df.iloc[idx+1:]['Close'] <= row['Distal'])[0]
            else:
              # breach_ind = np.where(htf_df.iloc[idx+1:]['High'] >= row['Distal'])[0]
              breach_ind = np.where(htf_df.iloc[idx+1:]['Close'] >= row['Distal'])[0]

            if breach_ind.size > 0:
              x1 = htf_df.index[breach_ind[0]+idx+1]

            y0, y1 = row['Proximal'], row['Distal']

            color = "rgba(0, 200, 0, 0.1)" if is_demand else "rgba(200, 0, 0, 0.1)"
            border_color = "green" if is_demand else "red"

            fig.add_shape(
                type="rect", x0=x0, y0=y0, x1=x1, y1=y1,
                fillcolor=color,
                line=dict(color=border_color, width=1, dash="dot"),
                layer="below",
                name="HTF Zone"
            )

    if show_trend:
      if htf_df is not None and not htf_df.empty and ('Trend' in htf_df.columns):
        trend_aligned = htf_df['Trend'].reindex(df.index, method='ffill').fillna(0)
      elif df is not None and not df.empty and ('Trend' in df.columns):
        trend_aligned = df['Trend']
      else:
        trend_aligned = None

      if trend_aligned is not None:
        up_indices = trend_aligned.index[trend_aligned == 1]
        fig.add_trace(go.Scatter(x=up_indices, y=df.loc[up_indices, 'High'] * 1.005,
                                  mode='markers', marker=dict(symbol='triangle-up', color='yellow', size=6),
                                name = 'Up Trend'))

        down_indices = trend_aligned.index[trend_aligned == -1]
        fig.add_trace(go.Scatter(x=down_indices, y=df.loc[down_indices, 'Low'] * 0.995,
                                  mode='markers', marker=dict(symbol='triangle-down', color='Red', size=6),
                                name = 'Down Trend'))

        side_indices = trend_aligned.index[trend_aligned == 0]
        fig.add_trace(go.Scatter(x=side_indices, y=df.loc[side_indices, ['Open','Close']].mean(axis=1) * 1,
                                  mode='markers', marker=dict(symbol='square', color='blue', size=6),
                                  name = 'Side Trend'))

    # 3. Add Zones from the DataFrame
    # We look for where Zone_Created is True to draw the boxes
    zone_indices = np.where(df['Zone_Created'] == True)[0]
    for idx in zone_indices:
        row = df.iloc[idx]
        is_demand = row['Is Demand']

        x0 = df.index[idx-1]
        if multibase:
          x0 = df.index[df['Base_Start_Idx'].iloc[idx]]

        x1 = df.index[-1]
        if is_demand:
          #  breach_ind = np.where(df.iloc[idx+1:]['Low'] <= row['Distal'])[0]
           breach_ind = np.where(df.iloc[idx+1:]['Close'] <= row['Distal'])[0]
        else:
          #  breach_ind = np.where(df.iloc[idx+1:]['High'] >= row['Distal'])[0]
           breach_ind = np.where(df.iloc[idx+1:]['Close'] >= row['Distal'])[0]

        if breach_ind.size > 0:
           x1 = df.index[breach_ind[0]+idx+1]

        y0 = row['Proximal']
        y1 = row['Distal']
        color = "rgba(0, 255, 0, 0.2)" if is_demand else "rgba(255, 0, 0, 0.2)"

        fig.add_shape(
            type="rect",
            x0=x0, y0=y0, x1=x1, y1=y1,
            fillcolor=color,
            line=dict(width=0),
            layer="below"
        )

    if show_swing:
        swing_indices = df.index[df['Swing_High'] == True]
        fig.add_trace(go.Scatter(x=swing_indices, y=df.loc[swing_indices, 'High'] * 1.005,
                                  mode='markers', marker=dict(symbol='triangle-up', color='yellow', size=8),
                                 name = 'Swing High'))
        swing_indices = df.index[df['Swing_Low'] == True]
        fig.add_trace(go.Scatter(x=swing_indices, y=df.loc[swing_indices, 'Low'] * 0.995,
                                  mode='markers', marker=dict(symbol='triangle-down', color='yellow', size=8),
                                 name = 'Swing Low'))

        confirm_shift = 0
        last_swing_high = df['High'].where(df['Swing_High']).ffill().shift(confirm_shift)
        last_swing_low = df['Low'].where(df['Swing_Low']).ffill().shift(confirm_shift)

        # Plot last swing high
        fig.add_trace(go.Scatter(x=last_swing_high.index, y=last_swing_high.values,
                                  mode='markers', marker=dict(symbol='x', color='blue', size=8),
                                 name = 'Last Swing High'))
        # Plot last swing low
        fig.add_trace(go.Scatter(x=last_swing_low.index, y=last_swing_low.values,
                                  mode='markers', marker=dict(symbol='x', color='red', size=8),
                                 name = 'Last Swing Low'))

    fig.update_layout(
        title=f"{ticker} - Demand & Supply Zones",
        xaxis_title="Date",
        yaxis_title="Price",
        xaxis_rangeslider_visible=False,
        height=600)

    fig.show()

def plot_stock_zones_monthly(ticker, df, multibase=True):
    fig = go.Figure()

    # 1. Candlestick Chart
    fig.add_trace(go.Candlestick(
        x=df.index.strftime('%Y-%m-%d'),
        open=df['Open'],
        high=df['High'],
        low=df['Low'],
        close=df['Close'],
        name='Price'
    ))

    # 2. Add Zones
    zone_indices = np.where(df['Zone_Created'] == True)[0]
    for idx in zone_indices:
        row = df.iloc[idx]
        x0 = df.index[idx-1].strftime('%Y-%m-%d')
        if multibase:
          x0 = df.index[df['Base_Start_Idx'].iloc[idx]].strftime('%Y-%m-%d')

        x1 = df.index[-1].strftime('%Y-%m-%d')
        if row['Is Demand']:
          #  breach_ind = np.where(df.iloc[idx+1:]['Low'] <= row['Distal'])[0]
           breach_ind = np.where(df.iloc[idx+1:]['Close'] <= row['Distal'])[0]
        else:
          #  breach_ind = np.where(df.iloc[idx+1:]['High'] >= row['Distal'])[0]
           breach_ind = np.where(df.iloc[idx+1:]['Close'] >= row['Distal'])[0]
        if breach_ind.size > 0:
           x1 = df.index[breach_ind[0]+idx+1].strftime('%Y-%m-%d')

        y0, y1 = row['Proximal'], row['Distal']
        color = "rgba(0, 255, 0, 0.2)" if row['Is Demand'] else "rgba(255, 0, 0, 0.2)"

        fig.add_shape(type="rect", x0=x0, y0=y0, x1=x1, y1=y1,
                      fillcolor=color, line=dict(width=0), layer="below")

    fig.update_layout(
        title=f"{ticker} - Monthly Zones (Fixed Spacing)",
        xaxis_title="Date",
        yaxis_title="Price",
        xaxis_rangeslider_visible=False,
        xaxis=dict(type='category'), # This fixes the 'squeezed' look
        height=600
    )
    fig.show()

def plot_backtest_results(ticker, df, summary_df):
    """Plots historical data with zones and backtest trade outcomes."""
    # Ensure dates are in category/string format for the candlestick if necessary
    # or use standard index
    fig = go.Figure()
    fig.add_trace(go.Candlestick(
        x=df.index,
        open=df['Open'],
        high=df['High'],
        low=df['Low'],
        close=df['Close'],
        name='Price'
    ))

    # Filter summary for the specific ticker
    ticker_summary = summary_df[summary_df['Ticker'] == ticker]

    for index, row in ticker_summary.iterrows():
        date_created = row['Date Created']
        entry_date = row['Entry Date']
        base_date = row['Date Base']
        exit_date = row['Exit Date']
        proximal = row['Proximal']
        distal = row['Distal']
        outcome = row['Outcome']
        target = row['Target']

        # Determine zone type and colors
        is_demand = target > proximal
        line_color = "lime" if is_demand else "red"
        zone_fill = "rgba(0, 255, 0, 0.2)" if is_demand else "rgba(255, 0, 0, 0.2)"

        # Draw the Zone Rectangle (from Base candle to Exit date)
        fig.add_shape(
            type="rect", x0=base_date, y0=proximal, x1=exit_date, y1=distal,
            line=dict(color=line_color, width=1),
            fillcolor=zone_fill, opacity=0.3, layer="below"
        )

        # Determine outcome level and color
        if outcome == "Profit":
            outcome_level = target
            outcome_color = "blue"
        elif outcome == "Stop Loss":
            outcome_level = distal
            outcome_color = "orange"
        else:
            outcome_level = None

        # Draw the Outcome Line
        if outcome_level is not None:
            fig.add_shape(
                type="line", x0=entry_date, y0=outcome_level, x1=exit_date, y1=outcome_level,
                line=dict(color=outcome_color, width=2, dash="dash")
            )

    fig.update_layout(
        title=f'{ticker} Backtest: Identified Zones and Trade Outcomes',
        yaxis_title='Price (INR)',
        xaxis_title='Date',
        xaxis_rangeslider_visible=False,
        height=700
    )
    fig.show(renderer="colab")

def plot_gap_candles(df,gap_threshold=1.0):
  gap = compute_gap_flags(zone_df)
  fig = go.Figure(data=[go.Candlestick(x=zone_df.index,
                  open=zone_df['Open'],
                  high=zone_df['High'],
                  low=zone_df['Low'],
                  close=zone_df['Close'],
                  name='Price')])

  # Filter for gaps to annotate on the plot
  # gap_threshold = 1.0
  sig_gap_indices = gap[gap > gap_threshold].index

  fig.add_trace(go.Scatter(
      x=sig_gap_indices,
      y=zone_df.loc[sig_gap_indices, 'Open'],
      mode='markers',
      marker=dict(symbol='triangle-up', size=10, color='blue'),
      name=f'Gap > {gap_threshold}*ATR'
  ))

  fig.update_layout(
      title=f'Price Chart with Significant Gaps Identified ({ticker})',
      yaxis_title='Price',
      xaxis_rangeslider_visible=False,
      height=700
  )
  fig.show()

  plt.figure(figsize=(12, 6))
  plt.plot(gap.index, gap.values, label='Gap / ATR')

  sig_gap_indices = gap[gap > gap_threshold]
  plt.scatter(sig_gap_indices.index, sig_gap_indices.values, color='red', marker='o', s=50, label=f'Significant Gaps (> {gap_threshold} * ATR)')

  plt.title('Gap (Open vs. Prior Close) as a Multiple of ATR')
  plt.xlabel('Date')
  plt.ylabel('Gap / ATR Multiple')
  plt.grid(True)
  plt.legend()
  plt.tight_layout()
  plt.show()

def plot_backtest_results_for_single(df, summary_df):
    """Plots historical data with zones and backtest trade outcomes."""
    # Ensure dates are in category/string format for the candlestick if necessary
    # or use standard index
    fig = go.Figure()
    fig.add_trace(go.Candlestick(
        x=df.index,
        open=df['Open'],
        high=df['High'],
        low=df['Low'],
        close=df['Close'],
        name='Price'
    ))

    # Filter summary for the specific ticker
    ticker_summary = summary_df

    for index, row in ticker_summary.iterrows():
        date_created = row['Date Created']
        entry_date = row['Entry Date']
        base_date = row['Date Base']
        exit_date = row['Exit Date']
        proximal = row['Proximal']
        distal = row['Distal']
        outcome = row['Outcome']
        target = row['Target']

        # Determine zone type and colors
        is_demand = target > proximal
        line_color = "lime" if is_demand else "red"
        zone_fill = "rgba(0, 255, 0, 0.2)" if is_demand else "rgba(255, 0, 0, 0.2)"

        # Draw the Zone Rectangle (from Base candle to Exit date)
        fig.add_shape(
            type="rect", x0=base_date, y0=proximal, x1=exit_date, y1=distal,
            line=dict(color=line_color, width=1),
            fillcolor=zone_fill, opacity=0.3, layer="below"
        )

        # Determine outcome level and color
        if outcome == "Profit":
            outcome_level = target
            outcome_color = "blue"
        elif outcome == "Stop Loss":
            outcome_level = distal
            outcome_color = "orange"
        else:
            outcome_level = None

        # Draw the Outcome Line
        if outcome_level is not None:
            fig.add_shape(
                type="line", x0=entry_date, y0=outcome_level, x1=exit_date, y1=outcome_level,
                line=dict(color=outcome_color, width=2, dash="dash")
            )

    fig.update_layout(
        title=f'Backtest: Identified Zones and Trade Outcomes',
        yaxis_title='Price (INR)',
        xaxis_title='Date',
        xaxis_rangeslider_visible=False,
        height=700
    )
    fig.show(renderer="colab")

"""### Performance Analysis Across All Tickers

First, let's consolidate all the `summary_df`s from `all_summary` into a single DataFrame for comprehensive analysis.
"""

def evaluate_strategy_metrics(summary_df):
    """
    Calculates key strategy evaluation metrics from a backtesting summary DataFrame.

    Args:
        summary_df (pd.DataFrame): DataFrame containing trade summaries with
                                   'Trade_PnL', 'Outcome', 'Entry Date', and 'Exit Date' columns.

    Returns:
        dict: A dictionary containing the calculated strategy metrics.
    """
    metrics = {}

    # 1. Net PNL
    metrics['Net PNL'] = summary_df['Trade_PnL'].sum()

    # Winning and Losing Trades
    winning_trades = summary_df[summary_df['Outcome'] == 'Profit']
    losing_trades = summary_df[summary_df['Outcome'] != 'Profit']

    # 2. Average profit per winning trade
    if not winning_trades.empty:
        metrics['Average Profit per Winning Trade'] = winning_trades['Trade_PnL'].mean()
    else:
        metrics['Average Profit per Winning Trade'] = 0.0

    # 3. Average loss per losing trade (as absolute value)
    if not losing_trades.empty:
        metrics['Average Loss per Losing Trade'] = abs(losing_trades['Trade_PnL'].mean())
    else:
        metrics['Average Loss per Losing Trade'] = 0.0

    # 4. Profit factor
    total_gross_profit = winning_trades['Trade_PnL'].sum()
    total_gross_loss = abs(losing_trades['Trade_PnL'].sum())
    if total_gross_loss > 0:
        metrics['Profit Factor'] = total_gross_profit / total_gross_loss
    else:
        metrics['Profit Factor'] = np.inf if total_gross_profit > 0 else 0.0

    # TOTAL ANAL
    total_trades = len(summary_df)
    win_rate = len(winning_trades) / total_trades if total_trades > 0 else 0.0
    loss_rate = 1 - win_rate
    metrics['Win Rate'] = win_rate*100.0
    metrics['Winning Trades'] = len(winning_trades)
    #metrics['Total Loss Rate'] = len(loss_rate)
    #metrics['Losing Trades'] = len(losing_trades)

    # 5. System expectancy
    avg_win = metrics['Average Profit per Winning Trade']
    avg_loss = metrics['Average Loss per Losing Trade']
    metrics['System Expectancy'] = (win_rate * avg_win) - (loss_rate * avg_loss)

    # 6. Expectancy score
    # Calculate days in backtest
    if not summary_df.empty:
        min_date = summary_df['Entry Date'].min()
        max_date = summary_df['Exit Date'].max()
        days_in_backtest = (max_date - min_date).days
    else:
        days_in_backtest = 1 # Avoid division by zero if no trades

    metrics['Expectancy Score'] = metrics['System Expectancy'] * total_trades * 365 / days_in_backtest if days_in_backtest > 0 else 0.0


    # 1. Absolute and Relative Zone Distribution
    demand_trades = summary_df[summary_df['Zone_Type'] == 'Demand']
    supply_trades = summary_df[summary_df['Zone_Type'] == 'Supply']

    dz_count = len(demand_trades)
    sz_count = len(supply_trades)

    metrics['Total Trades'] = total_trades
    metrics['Demand Zones'] = dz_count
    metrics['Supply Zones'] = sz_count

    # NEW: Global Profitability by Zone
    dz_wins = len(demand_trades[demand_trades['Outcome'] == 'Profit'])
    sz_wins = len(supply_trades[supply_trades['Outcome'] == 'Profit'])

    metrics['Profitable Demand Zones'] = dz_wins
    metrics['Profitable Supply Zones'] = sz_wins

    # 2. Timing Analysis
    summary_df['Entry Date'] = pd.to_datetime(summary_df['Entry Date'])
    summary_df['Date Created'] = pd.to_datetime(summary_df['Date Created'])
    summary_df['Exit Date'] = pd.to_datetime(summary_df['Exit Date'])

    summary_df['Time_Creation_to_Entry'] = (summary_df['Entry Date'] - summary_df['Date Created']).dt.days
    summary_df['Time_Entry_to_Exit'] = (summary_df['Exit Date'] - summary_df['Entry Date']).dt.days

    metrics['Avg Time Creation_Entry'] = summary_df['Time_Creation_to_Entry'].mean()

    profitable = summary_df[summary_df['Outcome'] == 'Profit']
    losing = summary_df[summary_df['Outcome'] == 'Stop Loss']


    metrics['Avg Hold Time (Profitable)'] = profitable['Time_Entry_to_Exit'].mean()
    metrics['Avg Hold Time (Losing)'] = losing['Time_Entry_to_Exit'].mean()
    avg_pierce = summary_df['Piercing_Depth'].mean() * 100
    metrics['Avg Piercing %'] = avg_pierce
    metrics['Avg PnL'] = summary_df['Trade_PnL'].mean()

    return metrics

"""### Global Strategy Composite Score
Applying the same logic to the overall portfolio performance to get a single baseline number for the strategy.
"""

def calculate_composite_score(row):
    """
    Calculates a single score from 0-100 based on multiple performance metrics.
    Weights:
    - Profit Factor: 35%
    - Expectancy: 25%
    - Win Rate: 20%
    - Efficiency (Days to Entry / Hold): 20%
    """
    #try:
        # Normalize Profit Factor (Cap at 5 for scoring purposes)
    pf_score = min(row['Profit Factor'] / 3.0, 1.0) * 35

    # Expectancy Score (Normalized against initial risk/100)
    exp_score = min(max(row['System Expectancy'] / 50.0, 0), 1.0) * 25

    # Win Rate
    wr_score = (row['Win Rate'] / 100.0) * 20

    # Efficiency Score (Inverse of Days to Entry - lower is better)
    # We assume > 60 days is 'slow'
    eff_score = max(0, (1 - (row['Avg Time Creation_Entry'] / 60.0))) * 20
    #print(pf_score,exp_score,wr_score,eff_score)

    total_score = pf_score + exp_score + wr_score + eff_score
    return round(total_score, 2)
    #except :
    #    return 0.0

# Constants
# Define parameters for the simulation
